/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Logger;
import java.util.logging.Level;

public class Acc_KRS_DosenPA extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(Acc_KRS_DosenPA.class.getName());

    public Acc_KRS_DosenPA() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilkanData();
    }

    private void tampilkanData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pengajuan");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("Semester");
        model.addColumn("Tahun Ajaran");

        try {
            Connection conn = new database().getConnection();
            
            // PERBAIKAN DI SINI: ganti k.id_dosen_pa menjadi m.id_dosen_pa
            String sql = "SELECT p.id_pengajuan, m.nama_mahasiswa, k.semester, k.tahun_ajaran " +
                         "FROM pengajuan_krs p " +
                         "JOIN mahasiswa m ON p.id_mahasiswa = m.id_mahasiswa " +
                         "JOIN krs k ON p.id_krs = k.id_krs " +
                         "WHERE p.status_acc = 'Ditinjau' AND m.id_dosen_pa = ?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, Session.getId()); // Pastikan Session.getId() adalah ID Dosen yang login
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_pengajuan"),
                    rs.getString("nama_mahasiswa"),
                    rs.getString("semester"),
                    rs.getString("tahun_ajaran")
                });
            }
            tabelAcc.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAcc = new javax.swing.JTable();
        btnAcc = new javax.swing.JButton();
        btnTolak = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Daftar Pengajuan KRS Mahasiswa Bimbingan");

        tabelAcc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelAcc);

        btnAcc.setText("Setujui");
        btnAcc.addActionListener(this::btnAccActionPerformed);

        btnTolak.setText("Revisi");
        btnTolak.addActionListener(this::btnTolakActionPerformed);

        btnDetail.setText("Lihat Detail");
        btnDetail.addActionListener(this::btnDetailActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAcc)
                            .addComponent(btnTolak)
                            .addComponent(btnDetail))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnAcc)
                        .addGap(32, 32, 32)
                        .addComponent(btnTolak)
                        .addGap(36, 36, 36)
                        .addComponent(btnDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(btnBack)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccActionPerformed
      int baris = tabelAcc.getSelectedRow();
        if (baris == -1) { JOptionPane.showMessageDialog(this, "Pilih mahasiswa!"); return; }

        String idPengajuan = tabelAcc.getValueAt(baris, 0).toString();
        
        try {
            Connection conn = new database().getConnection();
            String sql = "UPDATE pengajuan_krs SET status_acc = 'AccDosenPA' WHERE id_pengajuan = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, idPengajuan);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "KRS berhasil di-ACC!");
            tampilkanData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAccActionPerformed

    private void btnTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakActionPerformed
      int baris = tabelAcc.getSelectedRow();
        if (baris == -1) { JOptionPane.showMessageDialog(this, "Pilih mahasiswa!"); return; }

        String idPengajuan = tabelAcc.getValueAt(baris, 0).toString();
        String catatan = JOptionPane.showInputDialog(this, "Masukkan alasan penolakan/revisi:");
        
        if (catatan != null && !catatan.isEmpty()) {
            try {
                Connection conn = new database().getConnection();
                // Pastikan tabel pengajuan_krs punya kolom 'catatan_revisi'
                String sql = "UPDATE pengajuan_krs SET status_acc = 'Ditolak', catatan_revisi = ? WHERE id_pengajuan = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, catatan);
                ps.setString(2, idPengajuan);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "KRS telah ditolak.");
                tampilkanData();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnTolakActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        int baris = tabelAcc.getSelectedRow();
        if (baris == -1) { JOptionPane.showMessageDialog(this, "Pilih mahasiswa!"); return; }
        
        String idPengajuan = tabelAcc.getValueAt(baris, 0).toString();
        // Panggil Detail_KRS yang sudah kamu buat
        new Detail_KRS(this, true, idPengajuan).setVisible(true);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
       } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
    // Ubah 'logger' menjadi 'LOGGER' (huruf besar semua)
    LOGGER.log(java.util.logging.Level.SEVERE, null, ex); 
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Acc_KRS_DosenPA().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcc;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnTolak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelAcc;
    // End of variables declaration//GEN-END:variables
}
