/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class dashboard extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(dashboard.class.getName());

    public dashboard() {
        initComponents();
        this.setSize(1000, 635);
        this.setLocationRelativeTo(null);
        
        tampilkanJumlahBimbingan();
        
        // Ambil data dan bersihkan spasi
        String role = (Session.getRole() != null) ? Session.getRole().trim() : "";
        String nama = Session.getNama();
        String posisi = (Session.getPosisi() != null) ? Session.getPosisi().trim() : "";
        
        // Set teks selamat datang
        if (role.equalsIgnoreCase("Dosen")) {
            user.setText("Selamat Datang, " + posisi + " " + nama + "!");
        } else {
            user.setText("Selamat Datang, " + role + " " + nama + "!");
        }
        
        // Definisikan variabel boolean untuk kemudahan logika
        boolean isAdmin = role.equalsIgnoreCase("Admin");
        boolean isMahasiswa = role.equalsIgnoreCase("Mahasiswa");
        boolean isDosen = role.equalsIgnoreCase("Dosen");
        boolean isKaprodi = (isDosen && posisi.equalsIgnoreCase("Kaprodi"));
        boolean isDosenPA = (isDosen && posisi.equalsIgnoreCase("Dosen PA"));
        
        // 1. Master User HANYA untuk Admin
        Master.setVisible(isAdmin);
        
        // 2. Master Data HANYA untuk Admin
        btnMaster.setVisible(isAdmin);
        
        // 3. Jadwal Ajar HANYA untuk Dosen
        btnJadwalAjar.setVisible(isDosen);
        
        // 4. Finalisasi KRS HANYA untuk Kaprodi
        btnFinalisasiKRS.setVisible(isKaprodi);
        
        // 5. Mahasiswa PA HANYA untuk Dosen PA dan Kaprodi
        btnMahasiswaPA.setVisible(isDosenPA || isKaprodi);
        
        // 6. Riwayat KRS HANYA untuk Admin
        btnRiwayatKRS.setVisible(isAdmin);
        
        // 7. Data KRS: HANYA untuk Admin, Mahasiswa, Dosen PA, dan Kaprodi
        KRSButton.setVisible(isAdmin || isMahasiswa || isDosenPA || isKaprodi);
        
        // Edit Profile bisa diakses semua
        btnEditProfile.setVisible(true);
    }
    
    private void tampilkanJumlahBimbingan() {
        // Pastikan Session sudah menyimpan ID Dosen
        String idDosen = Session.getId(); 
        
        // Instansiasi database dan panggil method
        database db = new database();
        int jumlah = db.getJumlahBimbingan(idDosen);
    }
    
    // -----------------------
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Master = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMaster = new javax.swing.JButton();
        KRSButton = new javax.swing.JButton();
        btnJadwalAjar = new javax.swing.JButton();
        btnFinalisasiKRS = new javax.swing.JButton();
        btnEditProfile = new javax.swing.JButton();
        btnMahasiswaPA = new javax.swing.JButton();
        btnRiwayatKRS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Master.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Master.setText("Master User");
        Master.addActionListener(this::MasterActionPerformed);
        getContentPane().add(Master, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 190, 40));

        user.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        user.setText("Selamat Datang di Dashboard, ...");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 770, -1));

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logout.setText("Log Out");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Logout.addActionListener(this::LogoutActionPerformed);
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));
        Logout.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Pilih Fitur yang Ingin Digunakan:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnMaster.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMaster.setText("Master Data");
        btnMaster.addActionListener(this::btnMasterActionPerformed);
        getContentPane().add(btnMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 190, -1));

        KRSButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        KRSButton.setText("Data KRS");
        KRSButton.addActionListener(this::KRSButtonActionPerformed);
        getContentPane().add(KRSButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 190, -1));

        btnJadwalAjar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnJadwalAjar.setText("Jadwal Ajar");
        btnJadwalAjar.addActionListener(this::btnJadwalAjarActionPerformed);
        getContentPane().add(btnJadwalAjar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, -1));

        btnFinalisasiKRS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFinalisasiKRS.setText("Finalisasi KRS");
        btnFinalisasiKRS.addActionListener(this::btnFinalisasiKRSActionPerformed);
        getContentPane().add(btnFinalisasiKRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, -1));

        btnEditProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditProfile.setText("Edit Profile");
        btnEditProfile.addActionListener(this::btnEditProfileActionPerformed);
        getContentPane().add(btnEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, -1));

        btnMahasiswaPA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMahasiswaPA.setText("Mahasiswa PA");
        btnMahasiswaPA.addActionListener(this::btnMahasiswaPAActionPerformed);
        getContentPane().add(btnMahasiswaPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, -1));

        btnRiwayatKRS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRiwayatKRS.setText("Riwayat KRS");
        btnRiwayatKRS.addActionListener(this::btnRiwayatKRSActionPerformed);
        getContentPane().add(btnRiwayatKRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/home page (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
                               
       int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            new login_form().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void MasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterActionPerformed
   // Admin, Dosen, Mahasiswa semua boleh masuk ke Master User
    new masteruser().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_MasterActionPerformed

    private void btnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterActionPerformed
 String role = (Session.getRole() != null) ? Session.getRole().trim() : "";
        
        // --- LOGIKA ERROR JIKA BUKAN ADMIN ---
        if (role.equalsIgnoreCase("Admin")) {
            new masterdata().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Akses Ditolak! Hanya Admin yang memiliki akses ke Master Data.");
        }
    }//GEN-LAST:event_btnMasterActionPerformed

    private void KRSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KRSButtonActionPerformed
  String role = (Session.getRole() != null) ? Session.getRole().trim() : "";
    String posisi = (Session.getPosisi() != null) ? Session.getPosisi().trim() : ""; 

    if (role.equalsIgnoreCase("admin")) {
        new data_krs().setVisible(true);
        this.dispose();
    } 
    else if (role.equalsIgnoreCase("mahasiswa")) {
        // --- TAMBAHAN LOGIKA CEK DOSEN PA ---
        database db = new database();
        int idMhs = Integer.parseInt(Session.getId());
        
        // Panggil fungsi untuk cek apakah dosen_pa masih null/0
        if (db.getIdDosenPAMahasiswa(idMhs) == 0) {
            JOptionPane.showMessageDialog(this, 
                "Akses Ditolak! Dosen Pembimbing Akademik Anda belum ditentukan oleh Admin.\n" +
                "Silakan hubungi Admin untuk proses penugasan.", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Berhenti, form Pengajuan_KRS tidak terbuka
        }
        // Jika sudah ada Dosen PA, baru boleh lanjut
        new Pengajuan_KRS().setVisible(true);
        this.dispose();
    } 
    else if (role.equalsIgnoreCase("dosen") && (posisi.equalsIgnoreCase("Dosen PA") || posisi.equalsIgnoreCase("Kaprodi"))) {
        new Acc_KRS_DosenPA().setVisible(true); 
        this.dispose();
    }
    else {
        JOptionPane.showMessageDialog(this, "Role atau Posisi Anda tidak memiliki akses ke halaman KRS.");
    }
    }//GEN-LAST:event_KRSButtonActionPerformed

    private void btnJadwalAjarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalAjarActionPerformed
       new jadwal_ajar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJadwalAjarActionPerformed

    private void btnFinalisasiKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalisasiKRSActionPerformed
    // Buka Form Edit Profile
    new Finalisasi_KRS().setVisible(true);
    // Tutup Dashboard (karena nanti setelah save akan diarahkan ke login)
    this.dispose();
    }//GEN-LAST:event_btnFinalisasiKRSActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
    // Buka Form Edit Profile yang baru saja kita buat
        new FormEditProfile().setVisible(true);
        
        // Tutup Dashboard (karena nanti setelah save akan diarahkan otomatis ke login)
        this.dispose();
    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void btnMahasiswaPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMahasiswaPAActionPerformed
      String role = (Session.getRole() != null) ? Session.getRole().trim() : "";
        String posisi = (Session.getPosisi() != null) ? Session.getPosisi().trim() : "";

        // Double check keamanan
        if (role.equalsIgnoreCase("Dosen") && (posisi.equalsIgnoreCase("Dosen PA") || posisi.equalsIgnoreCase("Kaprodi"))) {
            new DataMahasiswaBimbingan().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Akses ditolak! Anda tidak memiliki hak akses ke menu Mahasiswa Bimbingan.");
        }
    }//GEN-LAST:event_btnMahasiswaPAActionPerformed

    private void btnRiwayatKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatKRSActionPerformed
    ArsipKRS_Admin arsipForm = new ArsipKRS_Admin();
    
    // Menampilkan form Arsip
    arsipForm.setVisible(true);
    }//GEN-LAST:event_btnRiwayatKRSActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KRSButton;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Master;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnFinalisasiKRS;
    private javax.swing.JButton btnJadwalAjar;
    private javax.swing.JButton btnMahasiswaPA;
    private javax.swing.JButton btnMaster;
    private javax.swing.JButton btnRiwayatKRS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
