/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class dashboard extends javax.swing.JFrame {
    // Tambahkan ini untuk menyimpan data sementara
    private String namaLogin;
    private String roleLogin;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }
// Pastikan Anda mengubah konstruktor yang INI, bukan public dashboard() yang kosong
    public dashboard(String namaUser, String role) {
    initComponents(); 
    this.namaLogin = namaUser; // Simpan ke variabel global
    this.roleLogin = role;     // Simpan ke variabel global

    // Set teks pada label variabel 'user'
    user.setText("Selamat datang di dashboard, " + namaUser + "!");

    this.setSize(1024, 640); 
    this.setLocationRelativeTo(null); 
}
    // -----------------------
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Master = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMaster = new javax.swing.JButton();
        KRSButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Master.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Master.setText("Master User");
        Master.addActionListener(this::MasterActionPerformed);
        getContentPane().add(Master, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, -1));

        user.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        user.setText("Selamat Datang di Dashboard, ...");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 770, -1));

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logout.setText("Log Out");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Logout.addActionListener(this::LogoutActionPerformed);
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));
        Logout.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Pilih Fitur yang Ingin Digunakan:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnMaster.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMaster.setText("Master Data");
        btnMaster.addActionListener(this::btnMasterActionPerformed);
        getContentPane().add(btnMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, -1));

        KRSButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        KRSButton.setText("Data KRS");
        KRSButton.addActionListener(this::KRSButtonActionPerformed);
        getContentPane().add(KRSButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/home page (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
                               
        // 1. Munculkan kotak pertanyaan
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin keluar?", 
                "Konfirmasi Keluar", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE);
        
        // 2. Jika user menjawab "Yes"
        if (konfirmasi == JOptionPane.YES_OPTION) {
            // Buka kembali halaman form login
            new login_form().setVisible(true);
            
            // Tutup halaman dashboard ini dengan aman
            dashboard.this.dispose(); 
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void MasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterActionPerformed
      try {
        // Kirim namaLogin dan roleLogin ke masteruser
        masteruser halMaster = new masteruser(namaLogin, roleLogin);
        
        halMaster.setVisible(true);
        halMaster.setLocationRelativeTo(null);
        this.dispose();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal pindah: " + e.getMessage());
    }

    }//GEN-LAST:event_MasterActionPerformed

    private void btnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterActionPerformed
    masterdata md = new masterdata(namaLogin, roleLogin); // Sesuaikan dengan variabel globalmu
    md.setVisible(true);
    md.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnMasterActionPerformed

    private void KRSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KRSButtonActionPerformed
    data_krs dk = new data_krs(namaLogin, roleLogin);
    dk.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_KRSButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KRSButton;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Master;
    private javax.swing.JButton btnMaster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
