/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;

public class DataMahasiswaBimbingan extends javax.swing.JFrame {

    private DefaultTableModel modelMhs;

   public DataMahasiswaBimbingan() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // 1. Kolom disederhanakan: Hanya identitas mahasiswa
        modelMhs = new DefaultTableModel(new String[]{"ID Mhs", "Nama", "Prodi", "Angkatan"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tabelMhs.setModel(modelMhs);
        aturLebarKolom(tabelMhs);
        loadDataBimbingan();
    }

    public void loadDataBimbingan() {
        modelMhs.setRowCount(0); 
        try {
            Connection conn = new database().getConnection();
            // 2. Query murni mengambil data mahasiswa saja (tanpa embel-embel KRS terbuka)
            String sql = "SELECT m.id_mahasiswa, m.nama_mahasiswa, pr.nama_prodi, m.angkatan " +
                         "FROM mahasiswa m " +
                         "LEFT JOIN prodi pr ON m.id_prodi = pr.id_prodi " + 
                         "WHERE m.id_dosen_pa = ?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, Session.getId()); 
            ResultSet rs = ps.executeQuery();
            
            while (rs.next()) {
                modelMhs.addRow(new Object[]{
                    rs.getString("id_mahasiswa"), // Kolom 0 sekarang adalah ID Mhs
                    rs.getString("nama_mahasiswa"),
                    rs.getString("nama_prodi"),
                    rs.getString("angkatan")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
 private void lihatDetailKRS(java.awt.event.ActionEvent evt) {
    int baris = tabelMhs.getSelectedRow();
    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih mahasiswa dulu!");
        return;
    }

    String idPengajuan = tabelMhs.getValueAt(baris, 0).toString();

    // Panggil Detail_KRS
    Detail_KRS dialog = new Detail_KRS(this, true, idPengajuan);
    dialog.setVisible(true);

    // Refresh tabel
    loadDataBimbingan();
}
 
 private void aturLebarKolom(javax.swing.JTable tabel) {
    TableColumnModel columnModel = tabel.getColumnModel();
    for (int col = 0; col < tabel.getColumnCount(); col++) {
        int width = 80; // Lebar minimal
        for (int row = 0; row < tabel.getRowCount(); row++) {
            TableCellRenderer renderer = tabel.getCellRenderer(row, col);
            Component comp = tabel.prepareRenderer(renderer, row, col);
            width = Math.max(comp.getPreferredSize().width + 15, width);
        }
        // Batasi maksimal agar tabel tidak terlalu lebar (misal 300px)
        columnModel.getColumn(col).setPreferredWidth(Math.min(width, 300));
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMhs = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Daftar Mahasiswa Bimbingan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        tabelMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelMhs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 800, 275));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 462, 150, 40));

        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDetail.setText("Lihat Detail");
        btnDetail.addActionListener(this::btnDetailActionPerformed);
        getContentPane().add(btnDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Rectangle (right).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
      int baris = tabelMhs.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih mahasiswa terlebih dahulu!");
            return;
        }

        // Ambil ID Mhs (sekarang ada di kolom 0)
        String idMhs = tabelMhs.getValueAt(baris, 0).toString();
        String namaMhs = tabelMhs.getValueAt(baris, 1).toString();
        
        // Panggil ArsipKRS_Admin dengan Constructor khusus
        ArsipKRS_Admin formArsip = new ArsipKRS_Admin(idMhs, namaMhs);
        formArsip.setVisible(true);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Kembali ke dashboard (sesuaikan dengan nama class dashboard kamu)
    new dashboard().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DataMahasiswaBimbingan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMhs;
    // End of variables declaration//GEN-END:variables
}
