/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.TableColumn;
import java.awt.Component;
import javax.swing.table.TableCellRenderer;

public class data_mahasiswa extends javax.swing.JFrame {
    
    // Variabel untuk filter (null jika admin, ada isinya jika mahasiswa)
    private String idMhsFilter = null;

    // 1. Constructor untuk Admin
    public data_mahasiswa() {
        initComponents();
        this.setLocationRelativeTo(null);
        aturHakAkses();
        tampilkan_data(); 
        
        // --- SATPAM PENGAMIDIL HAK AKSES ---
      if (Session.getRole() != null && Session.getRole().equalsIgnoreCase("mahasiswa")) {
            btnAdd.setVisible(false);
            btnDelete.setVisible(false);
            // Tombol Edit dibiarkan muncul karena mau dipakai buat edit data diri sendiri
        }
    }

    // 2. Constructor untuk Mahasiswa (Menerima ID dari masteruser)
    public data_mahasiswa(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idMhsFilter = id;
        aturHakAkses();
        tampilkan_data();
    }

    private void aturHakAkses() {
        String role = Session.getRole();
        if (role != null) {
            if (role.equalsIgnoreCase("Mahasiswa")) {
                btnAdd.setVisible(false);
                btnDelete.setVisible(false);
            } else if (role.equalsIgnoreCase("Dosen")) {
                btnAdd.setVisible(false);
                btnDelete.setVisible(false);
                btnEdit.setVisible(false);
            }
        }
    }

    private void tampilkan_data() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Mahasiswa");
        model.addColumn("Nama");
        model.addColumn("Prodi");
        model.addColumn("Dosen PA");
        model.addColumn("Angkatan");
        model.addColumn("Semester");

        try {
            Connection conn = new database().getConnection();
            String sql = "SELECT m.id_mahasiswa, m.nama_mahasiswa, p.nama_prodi, d.nama_dosen, m.angkatan, m.semester " +
                         "FROM mahasiswa m " +
                         "LEFT JOIN prodi p ON m.id_prodi = p.id_prodi " +
                         "LEFT JOIN dosen d ON m.id_dosen_pa = d.id_dosen";
            
            // Jika ada filter ID, tambahkan WHERE
            if (idMhsFilter != null) {
                sql += " WHERE m.id_mahasiswa = ?";
            }

            PreparedStatement ps = conn.prepareStatement(sql);
            if (idMhsFilter != null) {
                ps.setString(1, idMhsFilter);
            }

            ResultSet res = ps.executeQuery();
            while (res.next()) {
                // Perhatikan: Kita sekarang mengambil nama_prodi dan nama_dosen, bukan lagi id-nya
                String prodi = res.getString("nama_prodi");
                String dosen = res.getString("nama_dosen");
                
                model.addRow(new Object[]{
                    res.getString("id_mahasiswa"), 
                    res.getString("nama_mahasiswa"), 
                    res.getString("nama_prodi"), 
                    res.getString("nama_dosen"), 
                    res.getString("angkatan"),
                    res.getString("semester")
                });
            }
            tabelMhs.setModel(model);
            aturLebarKolom();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal load: " + e.getMessage());
        }
    }  
    
    private void aturLebarKolom() {
    for (int column = 0; column < tabelMhs.getColumnCount(); column++) {
        TableColumn tableColumn = tabelMhs.getColumnModel().getColumn(column);
        int preferredWidth = tableColumn.getMinWidth();
        
        for (int row = 0; row < tabelMhs.getRowCount(); row++) {
            TableCellRenderer cellRenderer = tabelMhs.getCellRenderer(row, column);
            Component c = tabelMhs.prepareRenderer(cellRenderer, row, column);
            int width = c.getPreferredSize().width + tabelMhs.getIntercellSpacing().width;
            preferredWidth = Math.max(preferredWidth, width);

            // Batasi agar tidak terlalu lebar (misal 300px)
            if (preferredWidth >= 300) {
                preferredWidth = 300;
                break;
            }
        }
        tableColumn.setPreferredWidth(preferredWidth);
    }
}
    /**
     * Creates new form data_mahasiswa
     */
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableMhs = new javax.swing.JScrollPane();
        tabelMhs = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMhsMouseClicked(evt);
            }
        });
        tableMhs.setViewportView(tabelMhs);

        getContentPane().add(tableMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 710, 500));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 220, -1));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 220, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 220, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Mahasiswa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int baris = tabelMhs.getSelectedRow();
        if (baris != -1) {
            // Ambil ID Mahasiswa dari kolom pertama (index 0)
            String idMhs = tabelMhs.getValueAt(baris, 0).toString();
            
            int opsi = JOptionPane.showConfirmDialog(this, "Yakin hapus Mahasiswa dengan ID: " + idMhs + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            
            if (opsi == JOptionPane.YES_OPTION) {
                try {
                    // Pakai id_mahasiswa sesuai kolom database kamu
                    String sql = "DELETE FROM mahasiswa WHERE id_mahasiswa='" + idMhs + "'";
                    
                    database db = new database(); 
                    Connection conn = db.getConnection();
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    
                    JOptionPane.showMessageDialog(this, "Data ID " + idMhs + " Berhasil Dihapus");
                    tampilkan_data(); 
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih dulu baris mahasiswa yang mau dihapus!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new masteruser().setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_backActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
int baris = tabelMhs.getSelectedRow();
    if (baris != -1) {
        // Gunakan fungsi bantu untuk mengambil nilai dengan aman
        String idMhs = getSafeValue(tabelMhs, baris, 0);
        String nama = getSafeValue(tabelMhs, baris, 1);
        String prodi = getSafeValue(tabelMhs, baris, 2);
        String dosen = getSafeValue(tabelMhs, baris, 3);
        String angkatan = getSafeValue(tabelMhs, baris, 4);
        String semester = getSafeValue(tabelMhs, baris, 5);

        String[] data = {idMhs, nama, prodi, dosen, angkatan, semester};

        FormTambahMahasiswa popup = new FormTambahMahasiswa(this, true, data);
        popup.setVisible(true);
        tampilkan_data(); 
    } else {
        JOptionPane.showMessageDialog(this, "Pilih dulu mahasiswa yang mau diedit!");
    }
}

// Fungsi BANTU untuk menghindari NullPointerException
private String getSafeValue(javax.swing.JTable table, int row, int col) {
    Object value = table.getValueAt(row, col);
    return (value == null) ? "" : value.toString();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMhsMouseClicked
   int baris = tabelMhs.getSelectedRow();
    if (baris == -1) return;

    String role = Session.getRole();
    
    // Jika Admin, selalu aktifkan tombol Edit
    if (role != null && role.equalsIgnoreCase("Admin")) {
        btnEdit.setEnabled(true);
    } 
    // Jika Mahasiswa, hanya aktifkan jika data yang diklik adalah milik dia sendiri
    else if (role != null && role.equalsIgnoreCase("Mahasiswa")) {
        String idBarisTerpilih = tabelMhs.getValueAt(baris, 0).toString();
        if (idBarisTerpilih.equals(idMhsFilter)) {
            btnEdit.setEnabled(true);
        } else {
            btnEdit.setEnabled(false);
        }
    }
    // Jika Dosen, biasanya tidak boleh edit, jadi biarkan disable
    else {
        btnEdit.setEnabled(false);
    }
    }//GEN-LAST:event_tabelMhsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     FormTambahMahasiswa popup = new FormTambahMahasiswa(this, true, null);
        popup.setVisible(true);
        
        // Ganti 'load_table' jadi 'tampilkan_data' sesuai nama fungsi kamu
        tampilkan_data();
    }//GEN-LAST:event_btnAddActionPerformed
    
        /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(data_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new data_mahasiswa().setVisible(true));
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tabelMhs;
    private javax.swing.JScrollPane tableMhs;
    // End of variables declaration//GEN-END:variables
}
