/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

public class data_mahasiswa extends javax.swing.JFrame {
    
    private String namaSesi, roleSesi;

    public data_mahasiswa(String nama, String role) {
        this.namaSesi = nama;
        this.roleSesi = role;
        initComponents();
        tampilkan_data(); 
    }

    public data_mahasiswa() {
        initComponents();
    }

    private void tampilkan_data() {
        DefaultTableModel model = new DefaultTableModel();
        // Menyesuaikan Header Tabel dengan Database kamu
        model.addColumn("ID Mahasiswa");
        model.addColumn("Nama");
        model.addColumn("ID Prodi");
        model.addColumn("ID Dosen PA");
        model.addColumn("Angkatan");

        try {
            String sql = "SELECT id_mahasiswa, nama_mahasiswa, id_prodi, id_dosen_pa, angkatan FROM mahasiswa";
            database db = new database(); 
            Connection conn = db.getConnection();
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);
            
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id_mahasiswa"), 
                    res.getString("nama_mahasiswa"), 
                    res.getString("id_prodi"), 
                    res.getString("id_dosen_pa"), 
                    res.getString("angkatan")
                });
            }
            tabelMhs.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal load data: " + e.getMessage());
        }
    }
    
    /**
     * Creates new form data_mahasiswa
     */
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableMhs = new javax.swing.JScrollPane();
        tabelMhs = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMhsMouseClicked(evt);
            }
        });
        tableMhs.setViewportView(tabelMhs);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        back.setText("Back");
        back.addActionListener(this::backActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete)
                            .addComponent(btnEdit)))
                    .addComponent(back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tableMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(back))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int baris = tabelMhs.getSelectedRow();
        if (baris != -1) {
            // Ambil ID Mahasiswa dari kolom pertama (index 0)
            String idMhs = tabelMhs.getValueAt(baris, 0).toString();
            
            int opsi = JOptionPane.showConfirmDialog(this, "Yakin hapus Mahasiswa dengan ID: " + idMhs + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            
            if (opsi == JOptionPane.YES_OPTION) {
                try {
                    // Pakai id_mahasiswa sesuai kolom database kamu
                    String sql = "DELETE FROM mahasiswa WHERE id_mahasiswa='" + idMhs + "'";
                    
                    database db = new database(); 
                    Connection conn = db.getConnection();
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    
                    JOptionPane.showMessageDialog(this, "Data ID " + idMhs + " Berhasil Dihapus");
                    tampilkan_data(); 
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih dulu baris mahasiswa yang mau dihapus!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    masteruser mu = new masteruser(namaSesi, roleSesi);
        mu.setVisible(true);
        mu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
int baris = tabelMhs.getSelectedRow();
    if (baris != -1) {
        // Ambil semua data dari baris yang dipilih
        String[] data = {
            tabelMhs.getValueAt(baris, 0).toString(), // id_mhs
            tabelMhs.getValueAt(baris, 1).toString(), // nama
            tabelMhs.getValueAt(baris, 2).toString(), // prodi
            tabelMhs.getValueAt(baris, 3).toString(), // dosen
            tabelMhs.getValueAt(baris, 4).toString()  // angkatan
        };

        // Panggil popup dengan membawa array data
        FormTambahMahasiswa popup = new FormTambahMahasiswa(this, true, data);
        popup.setVisible(true);
        tampilkan_data(); // Refresh tabel setelah popup tutup
    } else {
        JOptionPane.showMessageDialog(this, "Pilih dulu mahasiswa yang mau diedit!");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMhsMouseClicked
      
    }//GEN-LAST:event_tabelMhsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     FormTambahMahasiswa popup = new FormTambahMahasiswa(this, true, null);
        popup.setVisible(true);
        
        // Ganti 'load_table' jadi 'tampilkan_data' sesuai nama fungsi kamu
        tampilkan_data();
    }//GEN-LAST:event_btnAddActionPerformed
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(data_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new data_mahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JTable tabelMhs;
    private javax.swing.JScrollPane tableMhs;
    // End of variables declaration//GEN-END:variables
}
