/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author User
 */
public class data_jadwal extends javax.swing.JFrame {
    
    private String namaSesi, roleSesi; // Tambahkan variabel sesi
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(data_jadwal.class.getName());

    // Constructor Utama untuk menerima data dari masterdata
    public data_jadwal(String nama, String role) {
        this.namaSesi = nama;
        this.roleSesi = role;
        initComponents();
        tampilkan_data();
        this.setLocationRelativeTo(null);
    }

    // Constructor Kosong (Biar NetBeans tidak rewel)
    public data_jadwal() {
        initComponents();
        tampilkan_data();
    }

    private void tampilkan_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Mata Kuliah");
    model.addColumn("Dosen");
    model.addColumn("Hari");
    model.addColumn("Kelas");
    model.addColumn("Jam");
    model.addColumn("Ruang");

    try {
        Connection conn = new database().getConnection();
        // Query tanpa id_admin
        String sql = "SELECT jadwal.*, matkul.nama_matkul, dosen.nama_dosen FROM jadwal "
                   + "JOIN matkul ON jadwal.id_matkul = matkul.id_matkul "
                   + "JOIN dosen ON jadwal.id_dosen = dosen.id_dosen";
        
        ResultSet res = conn.createStatement().executeQuery(sql);
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_jadwal"),
                res.getString("nama_matkul"),
                res.getString("nama_dosen"),
                res.getString("hari"),
                res.getString("kelas"),
                res.getString("jam_mulai") + " - " + res.getString("jam_selesai"),
                res.getString("ruang")
            });
        }
        tabelJadwal.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelJadwal = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelJadwal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 710, 300));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 170, -1));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 170, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 170, -1));

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Jadwal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       masterdata md = new masterdata(namaSesi, roleSesi);
        md.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       FormTambahJadwal popup = new FormTambahJadwal(this, true);
        popup.setVisible(true);
        tampilkan_data();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int baris = tabelJadwal.getSelectedRow();
    if (baris != -1) {
        // Ambil semua data dari kolom tabel
        String[] data = {
            tabelJadwal.getValueAt(baris, 0).toString(), // id_jadwal
            tabelJadwal.getValueAt(baris, 1).toString(), // nama_matkul
            tabelJadwal.getValueAt(baris, 2).toString(), // nama_dosen
            tabelJadwal.getValueAt(baris, 3).toString(), // hari
            tabelJadwal.getValueAt(baris, 4).toString(), // kelas
            tabelJadwal.getValueAt(baris, 5).toString(), // jam (format: 00:00 - 00:00)
            tabelJadwal.getValueAt(baris, 6).toString()  // ruang
        };
        
        // Buka popup dengan membawa data
        FormTambahJadwal popup = new FormTambahJadwal(this, true, data);
        popup.setVisible(true);
        tampilkan_data(); // Refresh tabel setelah edit
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris jadwal yang mau diedit!");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       int baris = tabelJadwal.getSelectedRow();
    if (baris != -1) {
        String id = tabelJadwal.getValueAt(baris, 0).toString();
        int konfirm = JOptionPane.showConfirmDialog(this, "Hapus jadwal dengan ID " + id + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if (konfirm == JOptionPane.YES_OPTION) {
            try {
                Connection conn = new database().getConnection();
                PreparedStatement pst = conn.prepareStatement("DELETE FROM jadwal WHERE id_jadwal=?");
                pst.setString(1, id);
                pst.execute();
                
                JOptionPane.showMessageDialog(this, "Jadwal berhasil dihapus");
                tampilkan_data();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih jadwal yang mau dihapus!");
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new data_jadwal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelJadwal;
    // End of variables declaration//GEN-END:variables
}
