/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class data_prodi extends javax.swing.JFrame {
    private String namaSesi, roleSesi; // Tambahkan ini
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(data_prodi.class.getName());

    public data_prodi(String nama, String role) { // Constructor harus terima tamu
        this.namaSesi = nama;
        this.roleSesi = role;
        initComponents();
        tampilkan_data();
    }
    
    // Jangan hapus yang kosong, biarkan buat preview desain
    public data_prodi() {
        initComponents();
    }
    
    private void tampilkan_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Prodi");
    model.addColumn("Nama Program Studi");

    try {
        Connection conn = new database().getConnection();
        ResultSet res = conn.createStatement().executeQuery("SELECT * FROM prodi");
        while (res.next()) {
            model.addRow(new Object[]{res.getString("id_prodi"), res.getString("nama_prodi")});
        }
        tabelProdi.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProdi = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelProdi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelProdi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 660, 300));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 220, -1));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 220, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 220, -1));

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Prodi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    FormTambahProdi popup = new FormTambahProdi(this, true, null);
    popup.setVisible(true);
    tampilkan_data();
    }//GEN-LAST:event_btnAddActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    masterdata md = new masterdata(namaSesi, roleSesi);
    md.setVisible(true);
    md.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       int baris = tabelProdi.getSelectedRow();
    if (baris != -1) {
        String[] data = {
            tabelProdi.getValueAt(baris, 0).toString(),
            tabelProdi.getValueAt(baris, 1).toString()
        };
        FormTambahProdi popup = new FormTambahProdi(this, true, data);
        popup.setVisible(true);
        tampilkan_data();
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data prodi dulu!");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       int baris = tabelProdi.getSelectedRow();
    if (baris != -1) {
        // Ambil ID Prodi dari kolom pertama (index 0)
        String id = tabelProdi.getValueAt(baris, 0).toString();
        String nama = tabelProdi.getValueAt(baris, 1).toString();
        
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Hapus Program Studi: " + nama + "?", 
                "Konfirmasi Hapus", 
                JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = new database().getConnection();
                String sql = "DELETE FROM prodi WHERE id_prodi = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.execute();
                
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                tampilkan_data(); // Refresh tabel biar datanya hilang
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data prodi yang ingin dihapus!");
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new data_prodi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProdi;
    // End of variables declaration//GEN-END:variables
}
