/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.TableColumn;
import java.awt.Component;
import javax.swing.table.TableCellRenderer;

public class data_admin extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(data_admin.class.getName());

    public data_admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilkan_data();
    }

    private void tampilkan_data() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Admin");
        model.addColumn("Nama Admin");

        try {
            database db = new database();
            Connection conn = db.getConnection();
            String sql = "SELECT id_admin, nama_admin FROM admin";
            Statement st = conn.createStatement();
            ResultSet res = st.executeQuery(sql);
            
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id_admin"),
                    res.getString("nama_admin")
                });
            }
            tabelAdmin.setModel(model);
            aturLebarKolom();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal load data: " + e.getMessage());
        }
    }
    
    private void aturLebarKolom() {
    for (int column = 0; column < tabelAdmin.getColumnCount(); column++) {
        TableColumn tableColumn = tabelAdmin.getColumnModel().getColumn(column);
        int preferredWidth = tableColumn.getMinWidth();
        
        for (int row = 0; row < tabelAdmin.getRowCount(); row++) {
            TableCellRenderer cellRenderer = tabelAdmin.getCellRenderer(row, column);
            Component c = tabelAdmin.prepareRenderer(cellRenderer, row, column);
            int width = c.getPreferredSize().width + tabelAdmin.getIntercellSpacing().width;
            preferredWidth = Math.max(preferredWidth, width);

            // Batasi agar tidak terlalu lebar
            if (preferredWidth >= 300) {
                preferredWidth = 300;
                break;
            }
        }
        tableColumn.setPreferredWidth(preferredWidth);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAdmin = new javax.swing.JTable();
        bthAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelAdmin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 640, 490));

        bthAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bthAdd.setText("Add");
        bthAdd.addActionListener(this::bthAddActionPerformed);
        getContentPane().add(bthAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 190, -1));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 190, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 190, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Dosen (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       new masteruser().setVisible(true); // Panggil langsung
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void bthAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthAddActionPerformed
     // Membuka popup dengan parameter null karena data baru
    FormTambahAdmin popup = new FormTambahAdmin(this, true, null);
    popup.setVisible(true);
    tampilkan_data(); // Refresh tabel setelah popup ditutup
    }//GEN-LAST:event_bthAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int baris = tabelAdmin.getSelectedRow();
    if (baris != -1) {
        // Ambil data dari tabel untuk dikirim ke popup
        String[] data = {
            tabelAdmin.getValueAt(baris, 0).toString(), // id_admin
            tabelAdmin.getValueAt(baris, 1).toString()  // nama_admin
        };
        // Buka popup dengan membawa data lama
        FormTambahAdmin popup = new FormTambahAdmin(this, true, data);
        popup.setVisible(true);
        tampilkan_data(); // Refresh tabel
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris admin yang ingin diedit!");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      int baris = tabelAdmin.getSelectedRow();
        if (baris != -1) {
            // ID Admin yang dipilih di tabel untuk dihapus
            String idTarget = tabelAdmin.getValueAt(baris, 0).toString();
            
            // Mengambil ID Admin yang saat ini sedang login dari Session
            // Catatan: Sesuaikan pemanggilan method getId() ini dengan nama method di class Session Anda
            // (misalnya Session.getId(), Session.getIdAdmin(), atau Session.getUsername())
            String idLogin = Session.getId(); 
            
            // VALIDASI: Cek apakah ID yang mau dihapus sama dengan ID yang sedang login
            if (idTarget.equals(idLogin)) {
                JOptionPane.showMessageDialog(this, 
                    "Aksi ditolak! Anda tidak dapat menghapus akun Anda sendiri saat sedang login.", 
                    "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
                return; // Hentikan proses, jangan lanjutkan ke penghapusan
            }

            // Jika bukan diri sendiri, lanjutkan ke konfirmasi penghapusan
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Hapus Admin dengan ID " + idTarget + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    database db = new database();
                    Connection conn = db.getConnection();
                    String sql = "DELETE FROM admin WHERE id_admin = ?";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, idTarget);
                    pst.execute();
                    
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                    tampilkan_data(); // Refresh tabel
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new data_admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton bthAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelAdmin;
    // End of variables declaration//GEN-END:variables
}
