/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.Component;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author User
 */
public class data_matkul extends javax.swing.JFrame {
    // Variabel namaSesi dan roleSesi dihapus
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(data_matkul.class.getName());
    public data_matkul() {
        initComponents();
        tampilkan_data();
        this.setLocationRelativeTo(null);
    }

   private void tampilkan_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID MK");
    model.addColumn("Nama MK");
    model.addColumn("SKS");
    model.addColumn("Semester");
    model.addColumn("Prodi");

    try {
        Connection conn = new database().getConnection();
        String sql = "SELECT matkul.*, prodi.nama_prodi FROM matkul "
                   + "JOIN prodi ON matkul.id_prodi = prodi.id_prodi";
        ResultSet res = conn.createStatement().executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_matkul"), 
                res.getString("nama_matkul"),
                res.getString("sks"),
                res.getString("semester"),
                res.getString("nama_prodi")
            });
        }
        tabelMatkul.setModel(model);
        
        // PANGGIL DI SINI:
        aturLebarKolom(); 
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    
    private void aturLebarKolom() {
    for (int column = 0; column < tabelMatkul.getColumnCount(); column++) {
        TableColumn tableColumn = tabelMatkul.getColumnModel().getColumn(column);
        int preferredWidth = tableColumn.getMinWidth();
        
        for (int row = 0; row < tabelMatkul.getRowCount(); row++) {
            TableCellRenderer cellRenderer = tabelMatkul.getCellRenderer(row, column);
            Component c = tabelMatkul.prepareRenderer(cellRenderer, row, column);
            int width = c.getPreferredSize().width + tabelMatkul.getIntercellSpacing().width;
            preferredWidth = Math.max(preferredWidth, width);

            // Batasi maksimal agar tidak terlalu lebar
            if (preferredWidth >= 300) {
                preferredWidth = 300;
                break;
            }
        }
        tableColumn.setPreferredWidth(preferredWidth);
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMatkul = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelMatkul);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 670, 490));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 230, -1));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 230, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 230, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Matkul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        FormTambahMatkul popup = new FormTambahMatkul(this, true, null);
        popup.setVisible(true);
        tampilkan_data();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       int baris = tabelMatkul.getSelectedRow();
        if (baris != -1) {
            String[] data = {
                tabelMatkul.getValueAt(baris, 0).toString(), // id
                tabelMatkul.getValueAt(baris, 1).toString(), // nama
                tabelMatkul.getValueAt(baris, 2).toString(), // sks
                tabelMatkul.getValueAt(baris, 3).toString(), // semester
                tabelMatkul.getValueAt(baris, 4).toString()  // prodi
            };
            FormTambahMatkul popup = new FormTambahMatkul(this, true, data);
            popup.setVisible(true);
            tampilkan_data();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih mata kuliah dulu!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      int baris = tabelMatkul.getSelectedRow();
        if (baris != -1) {
            String id = tabelMatkul.getValueAt(baris, 0).toString();
            int opsi = JOptionPane.showConfirmDialog(this, "Hapus MK ID: " + id + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (opsi == JOptionPane.YES_OPTION) {
                try {
                    Connection conn = new database().getConnection();
                    // Sesuaikan nama kolom: id_mk atau id_matkul?
                    PreparedStatement pst = conn.prepareStatement("DELETE FROM matkul WHERE id_matkul=?");
                    pst.setString(1, id);
                    pst.execute();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    tampilkan_data();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      new masterdata().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new data_matkul().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMatkul;
    // End of variables declaration//GEN-END:variables
}
