/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.TableColumn;
import java.awt.Component;
import javax.swing.table.TableCellRenderer;

public class data_dosen extends javax.swing.JFrame {
    // Variabel penampung ID jika dipanggil untuk edit profil sendiri
    private String idDosenSpesifik = null;

    // Constructor Default (Untuk Admin)
    public data_dosen() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilkan_data();
    }

    // Constructor Baru (Untuk Dosen yang edit profilnya sendiri)
    public data_dosen(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idDosenSpesifik = id;
        tampilkan_data();
    }

    private void tampilkan_data() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Dosen");
        model.addColumn("Nama Dosen");
        model.addColumn("Posisi");

        try {
            database db = new database();
            Connection conn = db.getConnection();
            String sql;
            PreparedStatement ps;

            // LOGIKA FILTER: Jika idDosenSpesifik tidak null, berarti dosen yang buka profilnya sendiri
            if (idDosenSpesifik != null) {
                sql = "SELECT * FROM dosen WHERE id_dosen = ?";
                ps = conn.prepareStatement(sql);
                ps.setString(1, idDosenSpesifik);
            } else {
                // Admin lihat semua
                sql = "SELECT * FROM dosen";
                ps = conn.prepareStatement(sql);
            }

            ResultSet res = ps.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id_dosen"),
                    res.getString("nama_dosen"),
                    res.getString("posisi")
                });
            }
            tabelDosen.setModel(model);
            aturLebarKolom();
            // Tambahkan ini di bawah aturLebarKolom() jika ingin ID selalu ramping
            tabelDosen.getColumnModel().getColumn(0).setPreferredWidth(80);
            tabelDosen.getColumnModel().getColumn(0).setMaxWidth(100);
            db.disconnect();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal load data: " + e.getMessage());
        }
    }

   private void aturLebarKolom() {
    for (int column = 0; column < tabelDosen.getColumnCount(); column++) {
        TableColumn tableColumn = tabelDosen.getColumnModel().getColumn(column);
        int preferredWidth = tableColumn.getMinWidth();
        
        for (int row = 0; row < tabelDosen.getRowCount(); row++) {
            TableCellRenderer cellRenderer = tabelDosen.getCellRenderer(row, column);
            Component c = tabelDosen.prepareRenderer(cellRenderer, row, column);
            int width = c.getPreferredSize().width + tabelDosen.getIntercellSpacing().width;
            preferredWidth = Math.max(preferredWidth, width);

            // Batasi maksimal agar tidak terlalu lebar
            if (preferredWidth >= 300) {
                preferredWidth = 300;
                break;
            }
        }
        tableColumn.setPreferredWidth(preferredWidth);
    }
}

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDosen = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDosen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 630, 480));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 230, -1));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 230, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 230, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Dosen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    // Tambahkan 'null' di akhir agar cocok dengan constructor baru
    FormTambahDosen popup = new FormTambahDosen(this, true, null);
    popup.setVisible(true);
    tampilkan_data();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       int baris = tabelDosen.getSelectedRow();
        if (baris != -1) {
            String[] data = {
                tabelDosen.getValueAt(baris, 0).toString(),
                tabelDosen.getValueAt(baris, 1).toString(),
                tabelDosen.getValueAt(baris, 2).toString()
            };
            FormTambahDosen popup = new FormTambahDosen(this, true, data);
            popup.setVisible(true);
            tampilkan_data();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih dosen dulu!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       int baris = tabelDosen.getSelectedRow();
        if (baris != -1) {
            String idStr = tabelDosen.getValueAt(baris, 0).toString();
            int id = Integer.parseInt(idStr); // Ubah ke Int karena database.java butuhnya 'int'
            
            int opsi = JOptionPane.showConfirmDialog(this, "Hapus Dosen ID: " + id + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
            if (opsi == JOptionPane.YES_OPTION) {
                database db = new database();
                
                // PANGGIL FUNGSI DELETE DARI CLASS DATABASE
                boolean sukses = db.deleteDosen(id); 
                
                if (sukses) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    tampilkan_data(); // Refresh tabel
                } else {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus!");
                }
                
                db.disconnect(); // Tutup koneksi
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data dosen yang ingin dihapus terlebih dahulu!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    new masteruser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void tabelDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDosenMouseClicked
      int baris = tabelDosen.getSelectedRow();
    if (baris == -1) return;

    String idDosenTerpilih = tabelDosen.getValueAt(baris, 0).toString();

    // Jika yang login adalah Dosen, cek apakah ID-nya sama dengan baris yang diklik
    if (Session.getRole().equalsIgnoreCase("Dosen")) {
        if (idDosenTerpilih.equals(Session.getId())) {
            btnEdit.setEnabled(true); 
        } else {
            btnEdit.setEnabled(false);
        }
    }
    }//GEN-LAST:event_tabelDosenMouseClicked

   
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDosen;
    // End of variables declaration//GEN-END:variables
}
