/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author User
 */
public class data_dosen extends javax.swing.JFrame {
    private String namaSesi, roleSesi;
    // Deklarasi Logger agar tidak error di bagian bawah
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(data_dosen.class.getName());

    public data_dosen(String nama, String role) {
        this.namaSesi = nama;
        this.roleSesi = role;
        initComponents();
        tampilkan_data();
    }

    private void tampilkan_data() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Dosen");
        model.addColumn("Nama Dosen");
        model.addColumn("Posisi"); 

        try {
            database db = new database();
            Connection conn = db.getConnection();
            // Gunakan kolom 'posisi' sesuai database
            String sql = "SELECT id_dosen, nama_dosen, posisi FROM dosen";
            ResultSet res = conn.createStatement().executeQuery(sql);
            
            while (res.next()) {
                model.addRow(new Object[]{
                    res.getString("id_dosen"),
                    res.getString("nama_dosen"),
                    res.getString("posisi") 
                });
            }
            tabelDosen.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal load data: " + e.getMessage());
        }
    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDosen = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelDosen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 630, 320));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 230, -1));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 230, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 230, -1));

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Dosen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    // Tambahkan 'null' di akhir agar cocok dengan constructor baru
    FormTambahDosen popup = new FormTambahDosen(this, true, null);
    popup.setVisible(true);
    tampilkan_data();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       int baris = tabelDosen.getSelectedRow();
    if (baris != -1) {
        String[] data = {
            tabelDosen.getValueAt(baris, 0).toString(),
            tabelDosen.getValueAt(baris, 1).toString(),
            tabelDosen.getValueAt(baris, 2).toString()
        };
        // Masukkan array 'data' ke sini
        FormTambahDosen popup = new FormTambahDosen(this, true, data);
        popup.setVisible(true);
        tampilkan_data();
    } else {
        JOptionPane.showMessageDialog(this, "Pilih dosen dulu!");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris = tabelDosen.getSelectedRow();
        if (baris != -1) {
            String id = tabelDosen.getValueAt(baris, 0).toString();
            int opsi = JOptionPane.showConfirmDialog(this, "Hapus Dosen ID: " + id + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (opsi == JOptionPane.YES_OPTION) {
                try {
                    Connection conn = new database().getConnection();
                    PreparedStatement pst = conn.prepareStatement("DELETE FROM dosen WHERE id_dosen=?");
                    pst.setString(1, id);
                    pst.execute();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                    tampilkan_data();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    masteruser mu = new masteruser(namaSesi, roleSesi);
    mu.setVisible(true);
    mu.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDosen;
    // End of variables declaration//GEN-END:variables
}
