/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;

import javax.swing.table.DefaultTableModel;

public class Detail_KRS extends javax.swing.JDialog {

    private String idPengajuanAktif;

    // Konstruktor menerima ID Pengajuan yang dipilih
    public Detail_KRS(java.awt.Frame parent, boolean modal, String idPengajuan) {
        super(parent, modal);
        this.idPengajuanAktif = idPengajuan;
        initComponents();
        this.setLocationRelativeTo(null);
        
        tampilkanDetailKRS();
    }

    // Konstruktor default cadangan agar tidak eror di method main
    public Detail_KRS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

   private void tampilkanDetailKRS() {
       DefaultTableModel model = new DefaultTableModel();
        jTable1.setModel(model);
        
        model.addColumn("ID Detail");
        model.addColumn("Mata Kuliah");
        model.addColumn("SKS");
        model.addColumn("Kelas");
        model.addColumn("Hari");
        model.addColumn("Jam");
        model.addColumn("Ruang");

        try {
            java.sql.Connection conn = new database().getConnection();
            
            // PERBAIKAN: kd.id_krs_detail diganti menjadi kd.id_detail sesuai nama di phpMyAdmin!
            String sql = "SELECT kd.id_detail, m.nama_matkul, m.sks, k.nama_kelas, j.hari, j.jam_mulai, j.jam_selesai, r.nama_ruang " +
                         "FROM krs_detail kd " +
                         "JOIN jadwal j ON kd.id_jadwal = j.id_jadwal " +
                         "JOIN matkul m ON j.id_matkul = m.id_matkul " +
                         "LEFT JOIN kelas k ON j.kelas = k.id_kelas " +
                         "LEFT JOIN ruang r ON j.ruang = r.id_ruang " +
                         "WHERE kd.id_pengajuan = ?"; 
                         
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            
            // Menggunakan setString karena di databasemu tipe datanya VARCHAR
            ps.setString(1, idPengajuanAktif.trim()); 
            
            java.sql.ResultSet res = ps.executeQuery();
            
            while (res.next()) {
                String waktu = res.getString("jam_mulai") + " - " + res.getString("jam_selesai");
                model.addRow(new Object[]{
                    res.getString("id_detail"), // PERBAIKAN: Ini juga diganti jadi id_detail
                    res.getString("nama_matkul"),
                    res.getInt("sks"),
                    res.getString("nama_kelas"),
                    res.getString("hari"),
                    waktu,
                    res.getString("nama_ruang")
                });
            }
            
            jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "GAGAL LOAD DATA SQL: " + e.getMessage());
            e.printStackTrace();
        }
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabelDetail = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Tutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Daftar Mata Kuliah yang Diambil:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDetail.setViewportView(jTable1);

        Tutup.setText("Close");
        Tutup.addActionListener(this::TutupActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tutup)
                    .addComponent(jLabel1)
                    .addComponent(tabelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tutup)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutupActionPerformed
                                         
        this.dispose(); // Menutup jendela dialog pop-up saat tombol klik close
    
    }//GEN-LAST:event_TutupActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            // PERBAIKAN: Menggunakan pencatatan anonymous logger standar agar bebas error
            java.util.logging.Logger.getLogger("global").log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Detail_KRS dialog = new Detail_KRS(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tabelDetail;
    // End of variables declaration//GEN-END:variables
}
