/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class DialogDaftarMahasiswa extends javax.swing.JDialog {

    // Constructor custom untuk menangkap ID Jadwal dan Nama Matkul
    public DialogDaftarMahasiswa(java.awt.Frame parent, boolean modal, int idJadwal, String namaMatkul) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent); // Muncul tepat di tengah form induk
        
        lblJudulMatkul.setText("Daftar Mahasiswa - Mata Kuliah: " + namaMatkul);
        tampilkanData(idJadwal);
    }

    public DialogDaftarMahasiswa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

private void tampilkanData(int idJadwal) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NIM / ID");
    model.addColumn("Nama Mahasiswa");
    model.addColumn("Program Studi");
    model.addColumn("Angkatan");
    model.addColumn("Status KRS");
    tabelMahasiswa.setModel(model); 

    try {
        database db = new database();
        Connection conn = db.getConnection();
        
        // PERBAIKAN: Hubungkan mahasiswa ke tabel pengajuan_krs (pk), bukan ke krs (k)
        String sql = "SELECT m.id_mahasiswa AS nim, m.nama_mahasiswa AS nama, p.nama_prodi AS prodi, m.angkatan AS angk, k.status_krs AS status " +
                     "FROM krs_detail kd " +
                     "JOIN pengajuan_krs pk ON kd.id_pengajuan = pk.id_pengajuan " +
                     "JOIN krs k ON pk.id_krs = k.id_krs " +
                     "JOIN mahasiswa m ON pk.id_mahasiswa = m.id_mahasiswa " + // <-- PERBAIKANNYA DI SINI
                     "JOIN prodi p ON m.id_prodi = p.id_prodi " +
                     "WHERE kd.id_jadwal = ?";
        
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idJadwal);
        ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("nim"),
                res.getString("nama"),
                res.getString("prodi"),
                res.getString("angk"), 
                res.getString("status")
            });
        }
        db.disconnect();
        
    } catch (Exception e) {
        System.out.println("Error di DialogDaftarMahasiswa: " + e.getMessage());
        e.printStackTrace(); 
    }
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulMatkul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblJudulMatkul.setText("Daftar Mahasiswa");

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelMahasiswa);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblJudulMatkul)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblJudulMatkul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose(); // Perintah ini akan menutup layar pop-up
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(DialogDaftarMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogDaftarMahasiswa dialog = new DialogDaftarMahasiswa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudulMatkul;
    private javax.swing.JTable tabelMahasiswa;
    // End of variables declaration//GEN-END:variables
}
