/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableCellRenderer;
import java.awt.Component;

public class DialogDaftarMahasiswa extends javax.swing.JDialog {

    // Constructor custom untuk menangkap ID Jadwal dan Nama Matkul
    public DialogDaftarMahasiswa(java.awt.Frame parent, boolean modal, int idJadwal, String namaMatkul) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent); // Muncul tepat di tengah form induk
        
        lblJudulMatkul.setText("Daftar Mahasiswa - Mata Kuliah: " + namaMatkul);
        tampilkanData(idJadwal);
    }

    public DialogDaftarMahasiswa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

private void tampilkanData(int idJadwal) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NIM / ID");
    model.addColumn("Nama Mahasiswa");
    model.addColumn("Program Studi");
    model.addColumn("Angkatan");
    model.addColumn("Semester"); // Data Semester
    tabelMahasiswa.setModel(model); 
    
    try {
        database db = new database();
        Connection conn = db.getConnection();
        
        // Perbaikan: Ambil k.semester (dari tabel krs), bukan pk.semester
        String sql = "SELECT m.id_mahasiswa AS nim, m.nama_mahasiswa AS nama, " +
                     "p.nama_prodi AS prodi, m.angkatan AS angk, k.semester AS sem " +
                     "FROM krs_detail kd " +
                     "JOIN pengajuan_krs pk ON kd.id_pengajuan = pk.id_pengajuan " +
                     "JOIN krs k ON pk.id_krs = k.id_krs " + // Join ke krs untuk ambil semester
                     "JOIN mahasiswa m ON pk.id_mahasiswa = m.id_mahasiswa " +
                     "JOIN prodi p ON m.id_prodi = p.id_prodi " +
                     "WHERE kd.id_jadwal = ?";
        
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idJadwal);
        ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("nim"),
                res.getString("nama"),
                res.getString("prodi"),
                res.getString("angk"), 
                res.getString("sem") // Menampilkan semester dari alias 'sem'
            });
        }
        
        aturLebarKolom(tabelMahasiswa);
        db.disconnect();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error load data: " + e.getMessage());
        e.printStackTrace();
    }
}
   
private void aturLebarKolom(javax.swing.JTable tabel) {
    TableColumnModel columnModel = tabel.getColumnModel();
    for (int col = 0; col < tabel.getColumnCount(); col++) {
        int width = 80; // Lebar minimal
        for (int row = 0; row < tabel.getRowCount(); row++) {
            TableCellRenderer renderer = tabel.getCellRenderer(row, col);
            Component comp = tabel.prepareRenderer(renderer, row, col);
            width = Math.max(comp.getPreferredSize().width + 15, width);
        }
        // Batasi maksimal agar tabel tidak terlalu lebar (misal 300px)
        columnModel.getColumn(col).setPreferredWidth(Math.min(width, 300));
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulMatkul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudulMatkul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudulMatkul.setText("Daftar Mahasiswa");
        getContentPane().add(lblJudulMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelMahasiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 820, 300));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Rectangle (right).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose(); // Perintah ini akan menutup layar pop-up
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(DialogDaftarMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogDaftarMahasiswa dialog = new DialogDaftarMahasiswa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJudulMatkul;
    private javax.swing.JTable tabelMahasiswa;
    // End of variables declaration//GEN-END:variables
}
