/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.*;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import java.awt.Component;

public class Finalisasi_KRS extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(Finalisasi_KRS.class.getName());

    public Finalisasi_KRS() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilkanKRSMenungguFinalisasi();
        cekKunciAkses();
    }

  public void tampilkanKRSMenungguFinalisasi() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pengajuan");      // Index 0
    model.addColumn("Nama Mahasiswa");   // Index 1
    model.addColumn("Semester");         // Index 2
    model.addColumn("Dosen PA");         // Index 3
    
    try {
        database db = new database();
        int idDosenLogin = Integer.parseInt(Session.getId()); // Ambil ID Dosen dari Session
        int idProdi = db.getIdProdiByKaprodi(idDosenLogin); // Panggil fungsi baru tadi
        
        if (idProdi == -1) {
            JOptionPane.showMessageDialog(this, "Anda tidak terdaftar sebagai Kaprodi di prodi manapun.");
            return;
        }

        // Query join ke tabel mahasiswa untuk filter id_prodi
       // Ubah query di dalam method tampilkanKRSMenungguFinalisasi()
        String sql = "SELECT pk.id_pengajuan, m.nama_mahasiswa, k.semester, d.nama_dosen " +
             "FROM pengajuan_krs pk " +
             "JOIN mahasiswa m ON pk.id_mahasiswa = m.id_mahasiswa " +
             "JOIN krs k ON pk.id_krs = k.id_krs " +
             "LEFT JOIN dosen d ON m.id_dosen_pa = d.id_dosen " +
             "WHERE pk.status_acc = 'AccDosenPA' " +
             "AND m.id_prodi = ? " +
             "AND k.status_krs = 'terbuka'"; // KUNCI UTAMA: Hanya periode yang aktif saat ini
                     
        PreparedStatement ps = db.getConnection().prepareStatement(sql);
        ps.setInt(1, idProdi); // Filter berdasarkan prodi Kaprodi
        ResultSet res = ps.executeQuery();
        
       while (res.next()) {
        model.addRow(new Object[]{
            res.getString("id_pengajuan"), // Index 0
            res.getString("nama_mahasiswa"),// Index 1 (INI SEHARUSNYA NAMA)
            res.getString("semester"),     // Index 2
            res.getString("nama_dosen")    // Index 3
            });
        }
        tabelFinalisasi.setModel(model);
        aturLebarKolom(tabelFinalisasi);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error load data: " + e.getMessage());
    }
}
  
private void cekKunciAkses() {
    try {
        Connection conn = new database().getConnection();
        String sql = "SELECT id_krs FROM krs WHERE status_krs = 'terbuka' AND CURRENT_DATE BETWEEN tanggal_mulai AND tanggal_selesai";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        
        if (!rs.next()) {
            jLabel1.setText("Finalisasi (KRS DITUTUP - Mode Baca Saja)");
        } else {
            jLabel1.setText("Daftar KRS Mahasiswa yang Perlu Difinalisasi");
        }
    } catch (Exception e) {
        System.out.println("Error cek akses: " + e.getMessage());
    }
}

private void aturLebarKolom(javax.swing.JTable tabel) {
    TableColumnModel columnModel = tabel.getColumnModel();
    for (int col = 0; col < tabel.getColumnCount(); col++) {
        int width = 80; // Lebar minimal
        for (int row = 0; row < tabel.getRowCount(); row++) {
            TableCellRenderer renderer = tabel.getCellRenderer(row, col);
            Component comp = tabel.prepareRenderer(renderer, row, col);
            width = Math.max(comp.getPreferredSize().width + 15, width);
        }
        columnModel.getColumn(col).setPreferredWidth(Math.min(width, 300));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFinalisasi = new javax.swing.JTable();
        btnDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Daftar KRS Mahasiswa yang Perlu Difinalisasi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        tabelFinalisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelFinalisasi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 800, 280));

        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDetail.setText("Lihat Detail");
        btnDetail.addActionListener(this::btnDetailActionPerformed);
        getContentPane().add(btnDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 170, 40));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Rectangle (right).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
      // 1. Ambil baris yang dipilih
    int baris = tabelFinalisasi.getSelectedRow();
    
    // 2. Cek apakah ada baris yang dipilih
    if (baris == -1) {
        // Jika tidak ada, munculkan pesan popup
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu data KRS dari tabel terlebih dahulu!");
        return; // Hentikan eksekusi method
    }
    
    // 3. Jika sudah memilih, ambil data dan buka form detail
    String idPengajuan = tabelFinalisasi.getValueAt(baris, 0).toString();
    new Detail_KRS(this, true, idPengajuan).setVisible(true);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       new dashboard().setVisible(true); // Ganti sesuai nama kelas dashboard Kaprodi
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Finalisasi_KRS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelFinalisasi;
    // End of variables declaration//GEN-END:variables
}
