/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Logger;
import java.util.logging.Level;

public class Finalisasi_KRS extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(Finalisasi_KRS.class.getName());

    public Finalisasi_KRS() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilkanKRSMenungguFinalisasi();
    }

  private void tampilkanKRSMenungguFinalisasi() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pengajuan");      // Index 0
    model.addColumn("Nama Mahasiswa");   // Index 1
    model.addColumn("Semester");         // Index 2
    model.addColumn("Dosen PA");         // Index 3
    
    try {
        database db = new database();
        int idDosenLogin = Integer.parseInt(Session.getId()); // Ambil ID Dosen dari Session
        int idProdi = db.getIdProdiByKaprodi(idDosenLogin); // Panggil fungsi baru tadi
        
        if (idProdi == -1) {
            JOptionPane.showMessageDialog(this, "Anda tidak terdaftar sebagai Kaprodi di prodi manapun.");
            return;
        }

        // Query join ke tabel mahasiswa untuk filter id_prodi
        String sql = "SELECT pk.id_pengajuan, m.nama_mahasiswa, k.semester, d.nama_dosen " +
                     "FROM pengajuan_krs pk " +
                     "JOIN mahasiswa m ON pk.id_mahasiswa = m.id_mahasiswa " +
                     "JOIN krs k ON pk.id_krs = k.id_krs " +
                     "LEFT JOIN dosen d ON m.id_dosen_pa = d.id_dosen " +
                     "WHERE pk.status_acc = 'AccDosenPA' AND m.id_prodi = ?";
                     
        PreparedStatement ps = db.getConnection().prepareStatement(sql);
        ps.setInt(1, idProdi); // Filter berdasarkan prodi Kaprodi
        ResultSet res = ps.executeQuery();
        
       while (res.next()) {
        model.addRow(new Object[]{
            res.getString("id_pengajuan"), // Index 0
            res.getString("nama_mahasiswa"),// Index 1 (INI SEHARUSNYA NAMA)
            res.getString("semester"),     // Index 2
            res.getString("nama_dosen")    // Index 3
            });
        }
        tabelFinalisasi.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error load data: " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFinalisasi = new javax.swing.JTable();
        btnSetujui = new javax.swing.JButton();
        btnTolak = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Daftar KRS Mahasiswa yang Perlu Difinalisasi");

        tabelFinalisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelFinalisasi);

        btnSetujui.setText("Setujui");
        btnSetujui.addActionListener(this::btnSetujuiActionPerformed);

        btnTolak.setText("Revisi");
        btnTolak.addActionListener(this::btnTolakActionPerformed);

        btnDetail.setText("Lihat Detail");
        btnDetail.addActionListener(this::btnDetailActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSetujui)
                            .addComponent(btnTolak)
                            .addComponent(btnDetail))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnSetujui)
                        .addGap(55, 55, 55)
                        .addComponent(btnTolak)
                        .addGap(59, 59, 59)
                        .addComponent(btnDetail)))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetujuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetujuiActionPerformed
      int baris = tabelFinalisasi.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih KRS mahasiswa yang ingin difinalisasi!");
            return;
        }
        
        String idPengajuan = tabelFinalisasi.getValueAt(baris, 0).toString();
        String namaMhs = tabelFinalisasi.getValueAt(baris, 1).toString();
        
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Yakin ingin memfinalisasi KRS atas nama " + namaMhs + "?", 
                "Konfirmasi Finalisasi", JOptionPane.YES_NO_OPTION);
                
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = new database().getConnection();
                String sqlUpdate = "UPDATE pengajuan_krs SET status_acc = 'Disetujui' WHERE id_pengajuan = ?";
                PreparedStatement ps = conn.prepareStatement(sqlUpdate);
                ps.setString(1, idPengajuan);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "KRS berhasil difinalisasi!");
                tampilkanKRSMenungguFinalisasi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnSetujuiActionPerformed

    private void btnTolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolakActionPerformed
       int baris = tabelFinalisasi.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih KRS yang ingin ditolak!");
            return;
        }
        
        String idPengajuan = tabelFinalisasi.getValueAt(baris, 0).toString();
        String catatan = JOptionPane.showInputDialog(this, "Masukkan alasan revisi:");
        
        if (catatan != null && !catatan.trim().isEmpty()) {
            try {
                Connection conn = new database().getConnection();
                String sqlUpdate = "UPDATE pengajuan_krs SET status_acc = 'Ditolak', catatan_revisi = ? WHERE id_pengajuan = ?";
                PreparedStatement ps = conn.prepareStatement(sqlUpdate);
                ps.setString(1, catatan);
                ps.setString(2, idPengajuan);
                ps.executeUpdate();
                tampilkanKRSMenungguFinalisasi();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnTolakActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
       int baris = tabelFinalisasi.getSelectedRow();
        if (baris == -1) return;
        String idPengajuan = tabelFinalisasi.getValueAt(baris, 0).toString();
        new Detail_KRS(this, true, idPengajuan).setVisible(true);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       new dashboard().setVisible(true); // Ganti sesuai nama kelas dashboard Kaprodi
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Finalisasi_KRS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnSetujui;
    private javax.swing.JButton btnTolak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelFinalisasi;
    // End of variables declaration//GEN-END:variables
}
