/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author User
 */
public class FormTambahJadwal extends javax.swing.JDialog {
    private boolean isEdit = false;
    private String idJadwalEdit;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahJadwal.class.getName());

    /**
     * Creates new form FormTambahJadwal
     */
   
    // Pintu 1: Untuk Tambah Baru (btnAdd)
    public FormTambahJadwal(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null); // Melempar ke pintu 2 dengan data null
    }

    // Pintu 2: Untuk Edit (btnEdit) atau Tambah Baru (lewat pintu 1)
    public FormTambahJadwal(java.awt.Frame parent, boolean modal, String[] data) {
        super(parent, modal);
        initComponents();
        isiPilihanMatkul();
        isiPilihanDosen();
        
        if (data != null) {
            isEdit = true;
            idJadwalEdit = data[0];
            jLabel2.setText("Edit Jadwal Kuliah");
            cbMatkul.setSelectedItem(data[1]);
            cbDosen.setSelectedItem(data[2]);
            cbHari.setSelectedItem(data[3]);
            txtKelas.setText(data[4]);
            
            // Pecah jam "08:00:00 - 10:00:00"
            try {
                String[] jam = data[5].split(" - ");
                txtJamMulai.setText(jam[0]);
                txtJamSelesai.setText(jam[1]);
            } catch (Exception e) {
                // Jaga-jaga kalau format jam di tabel berbeda
            }
            
            txtRuang.setText(data[6]);
        }
        this.setLocationRelativeTo(null);
    }

private void isiPilihanMatkul() {
    try {
        Connection conn = new database().getConnection();
        ResultSet res = conn.createStatement().executeQuery("SELECT nama_matkul FROM matkul");
        cbMatkul.removeAllItems();
        while (res.next()) {
            cbMatkul.addItem(res.getString("nama_matkul"));
        }
    } catch (Exception e) {
        System.out.println("Gagal load matkul: " + e.getMessage());
    }
}

private void isiPilihanDosen() {
    try {
        Connection conn = new database().getConnection();
        ResultSet res = conn.createStatement().executeQuery("SELECT nama_dosen FROM dosen");
        cbDosen.removeAllItems();
        while (res.next()) {
            cbDosen.addItem(res.getString("nama_dosen"));
        }
    } catch (Exception e) {
        System.out.println("Gagal load dosen: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        cbMatkul = new javax.swing.JComboBox<>();
        cbDosen = new javax.swing.JComboBox<>();
        cbHari = new javax.swing.JComboBox<>();
        txtJamMulai = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtRuang = new javax.swing.JTextField();
        txtJamSelesai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Tambah Jadwal Baru:");

        jLabel1.setText("Mata Kuliah:");

        jLabel3.setText("Dosen Pengajar:");

        jLabel4.setText("Hari:");

        jLabel6.setText("Kelas:");

        jLabel7.setText("Ruang:");

        jLabel8.setText("Jam Mulai:");

        jLabel9.setText("Jam Selesai:");

        btnBatal.setText("Back");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        cbMatkul.addActionListener(this::cbMatkulActionPerformed);

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        txtJamMulai.setText("00:00:00");
        txtJamMulai.setToolTipText("");

        txtJamSelesai.setText("00:00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnBatal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSimpan))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(cbMatkul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDosen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtJamMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtJamSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMatkulActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      // --- LAPIS 1: VALIDASI INPUT KOSONG & RANGE JAM ---
    if (txtKelas.getText().isEmpty() || txtRuang.getText().isEmpty() || 
        txtJamMulai.getText().equals("00:00:00") || txtJamSelesai.getText().equals("00:00:00")) {
        JOptionPane.showMessageDialog(this, "Semua data wajib diisi!");
        return;
    }

    // Validasi Range Jam (00 - 23)
    try {
        String[] jm = txtJamMulai.getText().split(":");
        String[] js = txtJamSelesai.getText().split(":");
        int jamMulai = Integer.parseInt(jm[0]);
        int jamSelesai = Integer.parseInt(js[0]);

        if (jamMulai < 0 || jamMulai > 23 || jamSelesai < 0 || jamSelesai > 23) {
            JOptionPane.showMessageDialog(this, "Jam tidak valid! Gunakan range 00:00:00 sampai 23:59:59");
            return;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Format jam salah! Gunakan HH:mm:ss");
        return;
    }

    try {
        Connection conn = new database().getConnection();
        
        // --- LAPIS 2: CEK BENTROK JADWAL ---
        // Logika: Cari jadwal yang harinya sama DAN ruangnya sama DAN jamnya tumpang tindih
        String sqlCek = "SELECT * FROM jadwal WHERE hari = ? AND ruang = ? AND " +
                        "((jam_mulai <= ? AND jam_selesai > ?) OR (jam_mulai < ? AND jam_selesai >= ?))";
        
        // Jika sedang EDIT, jangan cek bentrok dengan dirinya sendiri
        if (isEdit) { sqlCek += " AND id_jadwal != " + idJadwalEdit; }

        PreparedStatement stCek = conn.prepareStatement(sqlCek);
        stCek.setString(1, cbHari.getSelectedItem().toString().toLowerCase());
        stCek.setString(2, txtRuang.getText());
        stCek.setString(3, txtJamMulai.getText());
        stCek.setString(4, txtJamMulai.getText());
        stCek.setString(5, txtJamSelesai.getText());
        stCek.setString(6, txtJamSelesai.getText());
        
        ResultSet rsCek = stCek.executeQuery();
        if (rsCek.next()) {
            JOptionPane.showMessageDialog(this, "JADWAL BENTROK!\nRuangan " + txtRuang.getText() + 
                    " sudah terpakai pada jam tersebut.");
            return; // Berhenti, jangan simpan
        }

        // --- LAPIS 3: EKSEKUSI SIMPAN ---
        // Ambil ID Matkul & Dosen (seperti kodingan sebelumnya)
        PreparedStatement psMk = conn.prepareStatement("SELECT id_matkul FROM matkul WHERE nama_matkul=?");
        psMk.setString(1, cbMatkul.getSelectedItem().toString());
        ResultSet rsMk = psMk.executeQuery();
        rsMk.next(); int idMk = rsMk.getInt("id_matkul");

        PreparedStatement psDs = conn.prepareStatement("SELECT id_dosen FROM dosen WHERE nama_dosen=?");
        psDs.setString(1, cbDosen.getSelectedItem().toString());
        ResultSet rsDs = psDs.executeQuery();
        rsDs.next(); int idDs = rsDs.getInt("id_dosen");

        String sql;
        if (isEdit) {
            sql = "UPDATE jadwal SET id_matkul=?, id_dosen=?, hari=?, kelas=?, jam_mulai=?, jam_selesai=?, ruang=? WHERE id_jadwal=?";
        } else {
            sql = "INSERT INTO jadwal (id_matkul, id_dosen, hari, kelas, jam_mulai, jam_selesai, ruang) VALUES (?, ?, ?, ?, ?, ?, ?)";
        }

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, idMk);
        pst.setInt(2, idDs);
        pst.setString(3, cbHari.getSelectedItem().toString().toLowerCase());
        pst.setString(4, txtKelas.getText());
        pst.setString(5, txtJamMulai.getText());
        pst.setString(6, txtJamSelesai.getText());
        pst.setString(7, txtRuang.getText());

        if (isEdit) { pst.setString(8, idJadwalEdit); }

        pst.execute();
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormTambahJadwal dialog = new FormTambahJadwal(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbDosen;
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtJamMulai;
    private javax.swing.JTextField txtJamSelesai;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtRuang;
    // End of variables declaration//GEN-END:variables
}
