/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;

import java.sql.*;
import javax.swing.JOptionPane;

public class FormTambahDosen extends javax.swing.JDialog {
    private boolean isEdit = false;
    // Tambahkan logger di sini juga
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahDosen.class.getName());
    

    // Constructor untuk Add dan Edit
    public FormTambahDosen(java.awt.Frame parent, boolean modal, String[] data) {
        super(parent, modal);
        initComponents();
        
        if (data != null) {
            isEdit = true;
            jLabel1.setText("Update Data Dosen");
            txtIdDosen.setText(data[0]);
            txtIdDosen.setEditable(false); // ID Dosen tidak boleh diubah saat edit
            txtNamaDosen.setText(data[1]);
            cbRole.setSelectedItem(data[2]);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtIdDosen = new javax.swing.JTextField();
        txtNamaDosen = new javax.swing.JTextField();
        cbRole = new javax.swing.JComboBox<>();
        txtPass = new javax.swing.JTextField();
        txtConfirmPass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Tambah Data Dosen Baru:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 37, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 71, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 105, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 133, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 167, -1, -1));

        btnBatal.setText("Back");
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));
        getContentPane().add(txtIdDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 360, -1));
        getContentPane().add(txtNamaDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 360, -1));

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dosen", "dosen pa", "kaprodi", " " }));
        getContentPane().add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 360, -1));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 360, -1));
        getContentPane().add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 360, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Add dosen.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      String pass = txtPass.getText();
        String confirm = txtConfirmPass.getText();

        if (!pass.equals(confirm)) {
            JOptionPane.showMessageDialog(this, "Password tidak cocok!");
            return;
        }

        try {
            database db = new database();
            Connection conn = db.getConnection();
            String sql;
            
            // Query menggunakan kolom 'posisi'
            if (isEdit) {
                sql = "UPDATE dosen SET nama_dosen=?, posisi=?, password=? WHERE id_dosen=?";
            } else {
                sql = "INSERT INTO dosen (nama_dosen, posisi, password, id_dosen) VALUES (?, ?, ?, ?)";
            }

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtNamaDosen.getText());
            pst.setString(2, cbRole.getSelectedItem().toString()); // Mengambil pilihan dari dropdown
            pst.setString(3, pass);
            pst.setString(4, txtIdDosen.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormTambahDosen dialog = new FormTambahDosen(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtConfirmPass;
    private javax.swing.JTextField txtIdDosen;
    private javax.swing.JTextField txtNamaDosen;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
