/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class FormTambahMahasiswa extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahMahasiswa.class.getName());

   // Tambahkan variabel ini di paling atas class
private boolean isEdit = false;

// Ubah Constructor agar bisa menerima data (Overloading)
public FormTambahMahasiswa(java.awt.Frame parent, boolean modal, String[] data) {
    super(parent, modal);
    initComponents();
    tampilkan_combobox();
    
    if (data != null) {
        isEdit = true;
        jLabel2.setText("Update Data Mahasiswa");
        txtId.setText(data[0]);
        txtId.setEditable(false); // ID tidak boleh diganti saat edit
        txtNama.setText(data[1]);
        cbProdi.setSelectedItem(data[2]);
        cbDosen.setSelectedItem(data[3]);
        txtAngkatan.setText(data[4]);
        // Password biarkan kosong atau isi jika perlu
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtAngkatan = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        cbProdi = new javax.swing.JComboBox<>();
        cbDosen = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID Mahasiswa:");

        jLabel2.setText("Tambah Data Mahasiswa Baru:");

        jLabel3.setText("Nama Mahasiswa:");

        jLabel4.setText("Program Studi:");

        jLabel5.setText("Dosen PA:");

        jLabel6.setText("Angkatan:");

        jLabel7.setText("Password:");

        btnBatal.setText("Back");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        jLabel8.setText("Confirm Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(228, 228, 228))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBatal)
                        .addGap(46, 46, 46)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId)
                    .addComponent(txtNama)
                    .addComponent(txtAngkatan)
                    .addComponent(txtPass)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpan))
                    .addComponent(cbProdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDosen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtConfirmPass))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
     // 1. Validasi Password
    String pass = txtPass.getText();
    String confirmPass = txtConfirmPass.getText();
    
    if (!pass.equals(confirmPass)) {
        JOptionPane.showMessageDialog(this, "Password dan Confirm Password tidak cocok!");
        return;
    }

    try {
        database db = new database();
        Connection conn = db.getConnection();

        // 2. LOGIKA AMBIL ID PRODI BERDASARKAN NAMA
        String namaProdi = cbProdi.getSelectedItem().toString();
        String sqlProdi = "SELECT id_prodi FROM prodi WHERE nama_prodi = ?";
        PreparedStatement pstProdi = conn.prepareStatement(sqlProdi);
        pstProdi.setString(1, namaProdi);
        ResultSet rsProdi = pstProdi.executeQuery();
        int idProdi = 0;
        if (rsProdi.next()) { idProdi = rsProdi.getInt("id_prodi"); }

        // 3. LOGIKA AMBIL ID DOSEN BERDASARKAN NAMA
        String namaDosen = cbDosen.getSelectedItem().toString();
        String sqlDosen = "SELECT id_dosen FROM dosen WHERE nama_dosen = ?";
        PreparedStatement pstDosen = conn.prepareStatement(sqlDosen);
        pstDosen.setString(1, namaDosen);
        ResultSet rsDosen = pstDosen.executeQuery();
        int idDosen = 0;
        if (rsDosen.next()) { idDosen = rsDosen.getInt("id_dosen"); }

        // 4. TENTUKAN SQL (INSERT atau UPDATE)
        String sql;
        if (isEdit) {
            sql = "UPDATE mahasiswa SET nama_mahasiswa=?, id_prodi=?, id_dosen_pa=?, angkatan=?, password=? WHERE id_mahasiswa=?";
        } else {
            sql = "INSERT INTO mahasiswa (nama_mahasiswa, id_prodi, id_dosen_pa, angkatan, password, id_mahasiswa) VALUES (?, ?, ?, ?, ?, ?)";
        }

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtNama.getText());
        pst.setInt(2, idProdi);
        pst.setInt(3, idDosen);
        pst.setString(4, txtAngkatan.getText());
        pst.setString(5, pass);
        pst.setString(6, txtId.getText());

        pst.execute();
        JOptionPane.showMessageDialog(null, isEdit ? "Data Berhasil Diupdate" : "Data Berhasil Disimpan");
        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
         this.dispose(); // Menutup popup tanpa simpan
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               FormTambahMahasiswa dialog = new FormTambahMahasiswa(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void tampilkan_combobox() {
        try {
            database db = new database();
            Connection conn = db.getConnection(); // Pastikan method di database.java namanya getConnection
            
            // Isi Dropdown Prodi
            cbProdi.removeAllItems();
            ResultSet resProdi = conn.createStatement().executeQuery("SELECT nama_prodi FROM prodi");
            while(resProdi.next()){
                cbProdi.addItem(resProdi.getString("nama_prodi"));
            }

            // Isi Dropdown Dosen
            cbDosen.removeAllItems();
            ResultSet resDosen = conn.createStatement().executeQuery("SELECT nama_dosen FROM dosen");
            while(resDosen.next()){
                cbDosen.addItem(resDosen.getString("nama_dosen"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load dropdown: " + e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbDosen;
    private javax.swing.JComboBox<String> cbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAngkatan;
    private javax.swing.JTextField txtConfirmPass;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables
}
