/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FormTambahProdi extends javax.swing.JDialog {
    private boolean isEdit = false; // Lahirkan variabel ini
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahProdi.class.getName());

    // Constructor Sakti (Bisa Add & Edit)
    public FormTambahProdi(java.awt.Frame parent, boolean modal, String[] data) {
    super(parent, modal);
    initComponents();
    loadDosenToDropdown(); // Panggil di sini
    // ... (kode lainnya)
        
        if (data != null) {
            isEdit = true;
            jLabel2.setText("Update Data Prodi");
            txtIdProdi.setText(data[0]);
            txtIdProdi.setEditable(false);
            txtNamaProdi.setText(data[1]);
        }
    }

    // Method untuk mengisi dropdown dengan data dosen
private void loadDosenToDropdown() {
    try {
        Connection conn = new database().getConnection();
        // Tambahkan WHERE untuk memfilter posisi
        String sql = "SELECT id_dosen, nama_dosen FROM dosen WHERE posisi = 'Kaprodi'";
        
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        
        cmbKaprodi.removeAllItems();
        cmbKaprodi.addItem("Pilih Kaprodi..."); 
        
        while (rs.next()) {
            cmbKaprodi.addItem(new Item(rs.getInt("id_dosen"), rs.getString("nama_dosen")));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}

// Class pembantu untuk menyimpan ID dan Nama di dalam ComboBox
class Item {
    private int id;
    private String nama;
    public Item(int id, String nama) { this.id = id; this.nama = nama; }
    public int getId() { return id; }
    @Override
    public String toString() { return nama; }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtIdProdi = new javax.swing.JTextField();
        txtNamaProdi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbKaprodi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Tambah Data Prodi Baru:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 45, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 79, -1, -1));

        btnBatal.setText("Back");
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));
        getContentPane().add(txtIdProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 430, -1));
        getContentPane().add(txtNamaProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 430, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        getContentPane().add(cmbKaprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 430, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Add Prodi.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       // Menutup jendela dialog saat tombol Back ditekan
    this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       // Validasi pemilihan dropdown
    if (cmbKaprodi.getSelectedItem() == null || cmbKaprodi.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Silakan pilih Kaprodi!");
        return;
    }

    Item selectedDosen = (Item) cmbKaprodi.getSelectedItem();

    try {
        Connection conn = new database().getConnection();
        String sql;
        if (isEdit) {
            sql = "UPDATE prodi SET nama_prodi=?, id_kaprodi=? WHERE id_prodi=?";
        } else {
            sql = "INSERT INTO prodi (nama_prodi, id_prodi, id_kaprodi) VALUES (?, ?, ?)";
        }

        PreparedStatement pst = conn.prepareStatement(sql);
        if (isEdit) {
            pst.setString(1, txtNamaProdi.getText());
            pst.setInt(2, selectedDosen.getId());
            pst.setString(3, txtIdProdi.getText());
        } else {
            pst.setString(1, txtNamaProdi.getText());
            pst.setString(2, txtIdProdi.getText());
            pst.setInt(3, selectedDosen.getId());
        }

        pst.executeUpdate(); // Gunakan executeUpdate() untuk INSERT/UPDATE
        JOptionPane.showMessageDialog(null, "Data Prodi Berhasil Disimpan");
        this.dispose();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace(); // Bantu cek detail error di console
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormTambahProdi dialog = new FormTambahProdi(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<Object> cmbKaprodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtIdProdi;
    private javax.swing.JTextField txtNamaProdi;
    // End of variables declaration//GEN-END:variables
}
