/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;

import java.sql.*;
import javax.swing.JOptionPane;

public class FormTambahMatkul extends javax.swing.JDialog {
    
    private boolean isEdit = false; // Biar tidak merah di bagian Simpan
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTambahMatkul.class.getName());

    // Constructor Sakti
    public FormTambahMatkul(java.awt.Frame parent, boolean modal, String[] data) {
        super(parent, modal);
        initComponents();
        isiComboProdi(); // Load prodi otomatis
        
        if (data != null) {
            isEdit = true;
            jLabel2.setText("Update Data Matkul");
            txtIdMK.setText(data[0]);
            txtIdMK.setEditable(false);
            txtNamaMK.setText(data[1]);
            txtSks.setText(data[2]); // Pastikan namanya txtSks
            txtSemester.setText(data[3]);
            cbProdi.setSelectedItem(data[4]);
        }
    }

    private void isiComboProdi() {
        try {
            Connection conn = new database().getConnection();
            ResultSet res = conn.createStatement().executeQuery("SELECT nama_prodi FROM prodi");
            cbProdi.removeAllItems();
            while (res.next()) {
                cbProdi.addItem(res.getString("nama_prodi"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load prodi: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtIdMK = new javax.swing.JTextField();
        txtNamaMK = new javax.swing.JTextField();
        txtSks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSemester = new javax.swing.JTextField();
        cbProdi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Tambah Data Matkul Baru:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 46, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 80, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 114, -1, -1));

        btnBatal.setText("Back");
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));
        getContentPane().add(txtIdMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 400, -1));
        getContentPane().add(txtNamaMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 400, -1));
        getContentPane().add(txtSks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 400, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 154, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 194, -1, -1));
        getContentPane().add(txtSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 400, -1));

        cbProdi.addActionListener(this::cbProdiActionPerformed);
        getContentPane().add(cbProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 400, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Add Matkul.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
     try {
        Connection conn = new database().getConnection();
        
        // Cari ID Prodi (tetap sama kodenya)
        String namaProdi = cbProdi.getSelectedItem().toString();
        PreparedStatement pstProdi = conn.prepareStatement("SELECT id_prodi FROM prodi WHERE nama_prodi = ?");
        pstProdi.setString(1, namaProdi);
        ResultSet rs = pstProdi.executeQuery();
        rs.next();
        int idProdi = rs.getInt("id_prodi");

        String sql;
        // GANTI 'mata_kuliah' MENJADI 'matkul' dan sesuaikan nama kolomnya
        if (isEdit) {
            sql = "UPDATE matkul SET nama_matkul=?, sks=?, semester=?, id_prodi=? WHERE id_matkul=?";
        } else {
            sql = "INSERT INTO matkul (nama_matkul, sks, semester, id_prodi, id_matkul) VALUES (?, ?, ?, ?, ?)";
        }

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtNamaMK.getText());
        pst.setString(2, txtSks.getText());
        pst.setString(3, txtSemester.getText());
        pst.setInt(4, idProdi);
        pst.setString(5, txtIdMK.getText());

        pst.execute();
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        this.dispose();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cbProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdiActionPerformed
       
    }//GEN-LAST:event_cbProdiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormTambahMatkul dialog = new FormTambahMatkul(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtIdMK;
    private javax.swing.JTextField txtNamaMK;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtSks;
    // End of variables declaration//GEN-END:variables
}
