/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;

import javax.swing.JOptionPane;

public class FormInputKelas extends javax.swing.JDialog {

    database db = new database();
    int idKelasEdit = 0;
    FormKelas parentForm;

    // Untuk Tambah Data
    public FormInputKelas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.parentForm = (FormKelas) parent;
    }

    // Untuk Edit Data
    public FormInputKelas(java.awt.Frame parent, boolean modal, int id, String nama) {
        super(parent, modal);
        initComponents();
        jLabel3.setText("Edit Data Kelas");
        setLocationRelativeTo(parent);
        this.parentForm = (FormKelas) parent;
        this.idKelasEdit = id;
        txtNamaKelas.setText(nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Teks = new javax.swing.JLabel();
        txtNamaKelas = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Tambah Kelas Baru:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        getContentPane().add(Teks, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 75, 82, -1));

        txtNamaKelas.addActionListener(this::txtNamaKelasActionPerformed);
        getContentPane().add(txtNamaKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 420, -1));

        btnBatal.setText("Back");
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Add Kelas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      String nama = txtNamaKelas.getText().trim();
        
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Kelas tidak boleh kosong!");
            return;
        }

        boolean sukses = (idKelasEdit == 0) ? db.tambahKelas(nama) : db.updateKelas(idKelasEdit, nama);

        if (sukses) {
            JOptionPane.showMessageDialog(this, "Data kelas berhasil disimpan!");
            parentForm.loadData();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data kelas!");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose(); // Langsung tutup form tanpa menyimpan
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNamaKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(FormInputKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormInputKelas dialog = new FormInputKelas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Teks;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNamaKelas;
    // End of variables declaration//GEN-END:variables
}
