/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PBO_Project_2;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import java.util.Date;

public class FormTambahJadwal extends javax.swing.JDialog {
    private boolean isEdit = false;
    private String idJadwalEdit;

    public FormTambahJadwal(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null); 
    }

    public FormTambahJadwal(java.awt.Frame parent, boolean modal, String[] data) {
        super(parent, modal);
        initComponents();
          this.setSize(610, 436); // Ganti angka ini sesuai ukuran desain aslimu
        
        // --- 1. MEMAKSA FORMAT JAM PADA JSPINNER ---
        javax.swing.JSpinner.DateEditor editorMulai = new javax.swing.JSpinner.DateEditor(spinJamMulai, "HH:mm:ss");
        spinJamMulai.setEditor(editorMulai);
        
        javax.swing.JSpinner.DateEditor editorSelesai = new javax.swing.JSpinner.DateEditor(spinJamSelesai, "HH:mm:ss");
        spinJamSelesai.setEditor(editorSelesai);
        
        // --- 2. MENGATUR WAKTU AWAL MENJADI 00:00:00 ---
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        Date waktuNol = cal.getTime();
        
        spinJamMulai.setValue(waktuNol);
        spinJamSelesai.setValue(waktuNol);
        
        // Load data dropdown dari master data
        isiPilihanMatkul();
        isiPilihanDosen();
        isiPilihanKelas();
        isiPilihanRuang();
        
        // Jika dalam mode EDIT, timpakan nilai dengan data lama yang dipilih dari tabel
        if (data != null) {
            isEdit = true;
            idJadwalEdit = data[0];
            jLabel2.setText("Edit Jadwal Kuliah");
            cbMatkul.setSelectedItem(data[1]);
            cbDosen.setSelectedItem(data[2]);
            cbHari.setSelectedItem(data[3]);
            cbKelas.setSelectedItem(data[4]); 
            
            try {
                String[] jam = data[5].split(" - ");
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm:ss");
                
                spinJamMulai.setValue(sdf.parse(jam[0]));
                spinJamSelesai.setValue(sdf.parse(jam[1]));
            } catch (Exception e) {
                System.out.println("Gagal load jam lama: " + e.getMessage());
            }
            
            cbRuang.setSelectedItem(data[6]); 
        }
        this.setLocationRelativeTo(null);
    }

    private void isiPilihanMatkul() {
        try {
            Connection conn = new database().getConnection();
            ResultSet res = conn.createStatement().executeQuery("SELECT nama_matkul FROM matkul");
            cbMatkul.removeAllItems();
            while (res.next()) cbMatkul.addItem(res.getString("nama_matkul"));
        } catch (Exception e) {}
    }

    private void isiPilihanDosen() {
        try {
            Connection conn = new database().getConnection();
            ResultSet res = conn.createStatement().executeQuery("SELECT nama_dosen FROM dosen");
            cbDosen.removeAllItems();
            while (res.next()) cbDosen.addItem(res.getString("nama_dosen"));
        } catch (Exception e) {}
    }

    private void isiPilihanKelas() {
        try {
            Connection conn = new database().getConnection();
            ResultSet res = conn.createStatement().executeQuery("SELECT nama_kelas FROM kelas");
            cbKelas.removeAllItems();
            while (res.next()) cbKelas.addItem(res.getString("nama_kelas"));
        } catch (Exception e) {}
    }

    private void isiPilihanRuang() {
        try {
            Connection conn = new database().getConnection();
            ResultSet res = conn.createStatement().executeQuery("SELECT nama_ruang FROM ruang");
            cbRuang.removeAllItems();
            while (res.next()) cbRuang.addItem(res.getString("nama_ruang"));
        } catch (Exception e) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        cbMatkul = new javax.swing.JComboBox<>();
        cbDosen = new javax.swing.JComboBox<>();
        cbHari = new javax.swing.JComboBox<>();
        cbKelas = new javax.swing.JComboBox<>();
        cbRuang = new javax.swing.JComboBox<>();
        spinJamMulai = new javax.swing.JSpinner();
        spinJamSelesai = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Tambah Jadwal Baru:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 53, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 87, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 127, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 368, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 411, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 368, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 411, -1, -1));

        btnBatal.setText("Back");
        btnBatal.addActionListener(this::btnBatalActionPerformed);
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        btnSimpan.setText("Save");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        cbMatkul.addActionListener(this::cbMatkulActionPerformed);
        getContentPane().add(cbMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 350, -1));
        getContentPane().add(cbDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 350, -1));

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        getContentPane().add(cbHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 350, -1));
        getContentPane().add(cbKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 160, -1));
        getContentPane().add(cbRuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 160, -1));

        spinJamMulai.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        getContentPane().add(spinJamMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 160, -1));

        spinJamSelesai.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        getContentPane().add(spinJamSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 160, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Add Jadwal.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMatkulActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    if (cbMatkul.getSelectedItem() == null || cbDosen.getSelectedItem() == null || 
            cbHari.getSelectedItem() == null || cbKelas.getSelectedItem() == null || cbRuang.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Semua data dropdown wajib dipilih!");
            return;
        }

        // Ambil string waktu dari JSpinner
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm:ss");
        String jamMulai = sdf.format(spinJamMulai.getValue());
        String jamSelesai = sdf.format(spinJamSelesai.getValue());

        // Validasi logika: Jam Selesai tidak boleh mendahului atau sama dengan Jam Mulai
        if (jamMulai.compareTo(jamSelesai) >= 0) {
            JOptionPane.showMessageDialog(this, "Waktu tidak valid! Jam Selesai harus setelah Jam Mulai.");
            return;
        }

        try {
            Connection conn = new database().getConnection();
            
            // --- CARI ID MASING-MASING MASTER DATA ---
            PreparedStatement psMk = conn.prepareStatement("SELECT id_matkul FROM matkul WHERE nama_matkul=?");
            psMk.setString(1, cbMatkul.getSelectedItem().toString());
            ResultSet rsMk = psMk.executeQuery(); rsMk.next(); int idMk = rsMk.getInt("id_matkul");

            PreparedStatement psDs = conn.prepareStatement("SELECT id_dosen FROM dosen WHERE nama_dosen=?");
            psDs.setString(1, cbDosen.getSelectedItem().toString());
            ResultSet rsDs = psDs.executeQuery(); rsDs.next(); int idDs = rsDs.getInt("id_dosen");

            PreparedStatement psKl = conn.prepareStatement("SELECT id_kelas FROM kelas WHERE nama_kelas=?");
            psKl.setString(1, cbKelas.getSelectedItem().toString());
            ResultSet rsKl = psKl.executeQuery(); rsKl.next(); int idKl = rsKl.getInt("id_kelas");

            PreparedStatement psRg = conn.prepareStatement("SELECT id_ruang FROM ruang WHERE nama_ruang=?");
            psRg.setString(1, cbRuang.getSelectedItem().toString());
            ResultSet rsRg = psRg.executeQuery(); rsRg.next(); int idRg = rsRg.getInt("id_ruang");

            // --- REVISI UTAMA: SAFETY CHECK 3 LAPIS BENTROK ---
            // Logika SQL: Mencari jadwal di hari yang sama, jam tumpang tindih, DAN (ruangnya sama ATAU dosennya sama ATAU kelasnya sama)
            String sqlCek = "SELECT j.*, m.nama_matkul, d.nama_dosen, k.nama_kelas, r.nama_ruang " +
                            "FROM jadwal j " +
                            "JOIN matkul m ON j.id_matkul = m.id_matkul " +
                            "JOIN dosen d ON j.id_dosen = d.id_dosen " +
                            "JOIN kelas k ON j.kelas = k.id_kelas " +
                            "JOIN ruang r ON j.ruang = r.id_ruang " +
                            "WHERE j.hari = ? AND " +
                            "((j.jam_mulai <= ? AND j.jam_selesai > ?) OR (j.jam_mulai < ? AND j.jam_selesai >= ?)) AND " +
                            "(j.ruang = ? OR j.id_dosen = ? OR j.kelas = ?)";
            
            // Jika sedang mengedit, abaikan pengecekan terhadap ID jadwal itu sendiri
            if (isEdit) { sqlCek += " AND j.id_jadwal != " + idJadwalEdit; }

            PreparedStatement stCek = conn.prepareStatement(sqlCek);
            stCek.setString(1, cbHari.getSelectedItem().toString().toLowerCase());
            stCek.setString(2, jamMulai); 
            stCek.setString(3, jamMulai);
            stCek.setString(4, jamSelesai);
            stCek.setString(5, jamSelesai);
            stCek.setInt(6, idRg);
            stCek.setInt(7, idDs);
            stCek.setInt(8, idKl);
            
            ResultSet rsCek = stCek.executeQuery();
            if (rsCek.next()) {
                // Analisis jenis bentrok apa yang terjadi untuk memberikan pesan spesifik ke pengguna
                String pesanError = "JADWAL BENTROK PADA JAM TERSEBUT!\n\nDetail Bentrok:";
                if (rsCek.getInt("ruang") == idRg) {
                    pesanError += "\n- Ruangan '" + cbRuang.getSelectedItem() + "' sudah terpakai.";
                }
                if (rsCek.getInt("id_dosen") == idDs) {
                    pesanError += "\n- Dosen '" + cbDosen.getSelectedItem() + "' sudah mengajar di kelas lain.";
                }
                if (rsCek.getInt("kelas") == idKl) {
                    pesanError += "\n- Kelas '" + cbKelas.getSelectedItem() + "' sudah memiliki jadwal kuliah lain (" + rsCek.getString("nama_matkul") + ").";
                }
                
                JOptionPane.showMessageDialog(this, pesanError, "Peringatan Sistem", JOptionPane.WARNING_MESSAGE);
                return; // Batalkan proses simpan
            }

            // --- EKSEKUSI DATA (INSERT / UPDATE) ---
            String sql;
            if (isEdit) {
                sql = "UPDATE jadwal SET id_matkul=?, id_dosen=?, hari=?, kelas=?, jam_mulai=?, jam_selesai=?, ruang=? WHERE id_jadwal=?";
            } else {
                sql = "INSERT INTO jadwal (id_matkul, id_dosen, hari, kelas, jam_mulai, jam_selesai, ruang) VALUES (?, ?, ?, ?, ?, ?, ?)";
            }

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, idMk);
            pst.setInt(2, idDs);
            pst.setString(3, cbHari.getSelectedItem().toString().toLowerCase());
            pst.setInt(4, idKl);
            pst.setString(5, jamMulai);
            pst.setString(6, jamSelesai);
            pst.setInt(7, idRg); 

            if (isEdit) { pst.setString(8, idJadwalEdit); }

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Jadwal Berhasil Disimpan!");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error sistem database: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(FormTambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormTambahJadwal dialog = new FormTambahJadwal(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbDosen;
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JComboBox<String> cbRuang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spinJamMulai;
    private javax.swing.JSpinner spinJamSelesai;
    // End of variables declaration//GEN-END:variables
}
