/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

public class jadwal_ajar extends javax.swing.JFrame {

    public jadwal_ajar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1000, 635);
        tampilkanJadwalSaya(); 
    }

 private void tampilkanJadwalSaya() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Jadwal");
    model.addColumn("Mata Kuliah");
    model.addColumn("SKS");
    model.addColumn("Waktu");
    model.addColumn("Kelas / Ruang");
    model.addColumn("Kuota");

    try {
        database db = new database();
        Connection conn = db.getConnection();
        
       String sql = "SELECT j.id_jadwal, mk.nama_matkul, mk.sks, j.hari, j.jam_mulai, j.jam_selesai, kl.nama_kelas, r.nama_ruang, " +
             "(SELECT COUNT(kd.id_detail) " +
             " FROM krs_detail kd " +
             " JOIN pengajuan_krs pk ON kd.id_pengajuan = pk.id_pengajuan " +
             " JOIN krs k ON pk.id_krs = k.id_krs " +
             " WHERE kd.id_jadwal = j.id_jadwal " +
             " AND pk.status_acc IN ('Ditinjau', 'Disetujui', 'AccDosenPA')) AS jumlah_mhs " + // PERBAIKAN: pk.status_acc
             "FROM jadwal j " +
             "JOIN matkul mk ON j.id_matkul = mk.id_matkul " +
             "JOIN dosen d ON j.id_dosen = d.id_dosen " +
             "JOIN kelas kl ON j.kelas = kl.id_kelas " +
             "JOIN ruang r ON j.ruang = r.id_ruang " +
             "WHERE d.nama_dosen = ?";
        
        // --- DETEKTIF: Cetak SQL ke Output untuk memastikan kode yang benar berjalan ---
        System.out.println("SQL yang dijalankan: " + sql);
        // ------------------------------------------------------------------------------

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, Session.getNama()); 
        ResultSet res = pst.executeQuery();

        while (res.next()) {
            String kuotaMhs = res.getInt("jumlah_mhs") + " / 40";
            model.addRow(new Object[]{
                res.getString("id_jadwal"), res.getString("nama_matkul"),
                res.getString("sks") + " SKS",
                res.getString("hari") + ", " + res.getString("jam_mulai") + "-" + res.getString("jam_selesai"),
                res.getString("nama_kelas") + " / " + res.getString("nama_ruang"),
                kuotaMhs
            });
        }
        tabelJadwalAjar.setModel(model);
        // Tambahkan ini:
          aturLebarKolom();
        db.disconnect();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat jadwal: " + e.getMessage());
        e.printStackTrace(); 
    }
}
 
 private void aturLebarKolom() {
    for (int column = 0; column < tabelJadwalAjar.getColumnCount(); column++) {
        TableColumn tableColumn = tabelJadwalAjar.getColumnModel().getColumn(column);
        int preferredWidth = tableColumn.getMinWidth();
        int maxWidth = tableColumn.getMaxWidth();

        for (int row = 0; row < tabelJadwalAjar.getRowCount(); row++) {
            TableCellRenderer cellRenderer = tabelJadwalAjar.getCellRenderer(row, column);
            Component c = tabelJadwalAjar.prepareRenderer(cellRenderer, row, column);
            int width = c.getPreferredSize().width + tabelJadwalAjar.getIntercellSpacing().width;
            preferredWidth = Math.max(preferredWidth, width);

            // Batasi agar tidak terlalu lebar (misal max 300px)
            if (preferredWidth >= 300) {
                preferredWidth = 300;
                break;
            }
        }
        tableColumn.setPreferredWidth(preferredWidth);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelJadwalAjar = new javax.swing.JTable();
        btnLihatMahasiswa = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Halaman Jadwal Mengajar Dosen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        tabelJadwalAjar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelJadwalAjar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 820, 310));

        btnLihatMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLihatMahasiswa.setText("Lihat Daftar Mahasiswa");
        btnLihatMahasiswa.addActionListener(this::btnLihatMahasiswaActionPerformed);
        getContentPane().add(btnLihatMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 472, 240, 40));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 140, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Rectangle (right).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatMahasiswaActionPerformed
        int baris = tabelJadwalAjar.getSelectedRow();
        if (baris != -1) {
            // Ambil ID Jadwal dan Nama Matkul dari baris yang diklik
            int idJadwal = Integer.parseInt(tabelJadwalAjar.getValueAt(baris, 0).toString());
            String namaMatkul = tabelJadwalAjar.getValueAt(baris, 1).toString();
            
            // Panggil Pop-up Dialog
            DialogDaftarMahasiswa popup = new DialogDaftarMahasiswa(this, true, idJadwal, namaMatkul);
            popup.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Silakan klik/pilih salah satu jadwal di tabel terlebih dahulu!");
        }
    }//GEN-LAST:event_btnLihatMahasiswaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new dashboard().setVisible(true); // Panggil langsung
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            // INI YANG BENAR: Ditaruh di dalam catch
            java.util.logging.Logger.getLogger(jadwal_ajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // INI PENTING: Untuk memunculkan halamannya
        java.awt.EventQueue.invokeLater(() -> new jadwal_ajar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLihatMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelJadwalAjar;
    // End of variables declaration//GEN-END:variables
}
