/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

public class masteruser extends javax.swing.JFrame {
    private static final Logger LOGGER = Logger.getLogger(masteruser.class.getName());

   public masteruser() {
    initComponents();
    this.setLocationRelativeTo(null);
    
    String role = Session.getRole();
    
    // Sembunyikan tombol Data Admin untuk selain Admin
    btnAdmin.setVisible(role.equalsIgnoreCase("Admin"));
    
    // Jika Mahasiswa, sembunyikan tombol Dosen & Admin
    if (role.equalsIgnoreCase("Mahasiswa")) {
        btnDos.setVisible(false);
        btnAdmin.setVisible(false);
    }
    
    // Jika Dosen, sembunyikan tombol Mahasiswa & Admin
    if (role.equalsIgnoreCase("Dosen")) {
        btnMahasiswa.setVisible(false);
        btnAdmin.setVisible(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMahasiswa = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMahasiswa.setText("Data Mahasiswa");
        btnMahasiswa.addActionListener(this::btnMahasiswaActionPerformed);
        getContentPane().add(btnMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 300, 40));

        btnDos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDos.setText("Data Dosen");
        btnDos.addActionListener(this::btnDosActionPerformed);
        getContentPane().add(btnDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 300, -1));

        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdmin.setText("Data Admin");
        btnAdmin.setToolTipText("");
        btnAdmin.addActionListener(this::btnAdminActionPerformed);
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 300, -1));

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Master User.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
   new dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMahasiswaActionPerformed
     String role = Session.getRole();
    
    // UBAH LOGIKA: Admin boleh buka semua, Mahasiswa boleh buka dirinya sendiri
    if (role.equalsIgnoreCase("Admin")) {
        new data_mahasiswa().setVisible(true); // Admin buka tanpa filter
        this.dispose();
    } else if (role.equalsIgnoreCase("Mahasiswa")) {
        // Mahasiswa hanya bisa buka data_mahasiswa yang memfilter ID dirinya
        new data_mahasiswa(Session.getId()).setVisible(true); 
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Akses Ditolak!");
    }
    }//GEN-LAST:event_btnMahasiswaActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
 String role = Session.getRole();
    
    if (role.equalsIgnoreCase("Admin")) {
        new data_dosen().setVisible(true);
        this.dispose();
    } else if (role.equalsIgnoreCase("Dosen")) {
        // Dosen hanya bisa buka data_dosen yang memfilter ID dirinya
        new data_dosen(Session.getId()).setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Akses Ditolak!");
    }
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
   new data_admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new masteruser().setVisible(true));
    }
        //</editor-fold>


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnMahasiswa;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
