/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

public class masterdata extends javax.swing.JFrame {
    private String namaSesi, roleSesi;
    // Tambahkan deklarasi logger ini
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(masterdata.class.getName());

    // Constructor untuk menerima kiriman data sesi
    public masterdata(String nama, String role) {
        this.namaSesi = nama;
        this.roleSesi = role;
        initComponents();
        this.setLocationRelativeTo(null); // Biar muncul di tengah layar
    }

    // Constructor kosong agar preview NetBeans tidak error
    public masterdata() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProdi = new javax.swing.JButton();
        btnMatkul = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 6, -1, -1));

        btnProdi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnProdi.setText("Data Prodi");
        btnProdi.addActionListener(this::btnProdiActionPerformed);
        getContentPane().add(btnProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, -1));

        btnMatkul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMatkul.setText("Data Matkul");
        btnMatkul.addActionListener(this::btnMatkulActionPerformed);
        getContentPane().add(btnMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 280, -1));

        btnJadwal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnJadwal.setText("Data Jadwal");
        btnJadwal.addActionListener(this::btnJadwalActionPerformed);
        getContentPane().add(btnJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 280, -1));

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.setToolTipText("");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Master Data.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdiActionPerformed
      data_prodi dp = new data_prodi(namaSesi, roleSesi);
       dp.setVisible(true);
       dp.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_btnProdiActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       dashboard db = new dashboard(namaSesi, roleSesi);
       db.setVisible(true);
       db.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatkulActionPerformed
    data_matkul dm = new data_matkul(namaSesi, roleSesi);
    dm.setVisible(true);
    dm.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnMatkulActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
    data_jadwal dm = new data_jadwal(namaSesi, roleSesi);
    dm.setVisible(true);
    dm.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnJadwalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new masterdata().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnMatkul;
    private javax.swing.JButton btnProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
