/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

/**
 *
 * @author TUF
 */
public class masteruser extends javax.swing.JFrame {
    private String namaSesi;
    private String roleSesi;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(masteruser.class.getName());

    /**
     * Creates new form masteruser
     */
 
    public masteruser() {
    initComponents();
}
    
    public masteruser(String nama, String role) {
    this.namaSesi = nama; // Terima titipan nama
    this.roleSesi = role; // Terima titipan role
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMahasiswa = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMahasiswa.setText("Data Mahasiswa");
        btnMahasiswa.addActionListener(this::btnMahasiswaActionPerformed);

        btnDos.setText("Data Dosen");
        btnDos.addActionListener(this::btnDosActionPerformed);

        btnAdmin.setText("Data Admin");
        btnAdmin.setToolTipText("");
        btnAdmin.addActionListener(this::btnAdminActionPerformed);

        back.setText("Back");
        back.addActionListener(this::backActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pilih Data Yang Ingin Diubah:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(back)
                    .addComponent(btnDos)
                    .addComponent(btnMahasiswa)
                    .addComponent(btnAdmin))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMahasiswa)
                .addGap(18, 18, 18)
                .addComponent(btnDos)
                .addGap(18, 18, 18)
                .addComponent(btnAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    // Panggil dashboard kembali dengan membawa namaSesi dan roleSesi
    dashboard balik = new dashboard(namaSesi, roleSesi);
    
    balik.setVisible(true);
    balik.setLocationRelativeTo(null);
    this.dispose(); // Tutup masteruser
    }//GEN-LAST:event_backActionPerformed

    private void btnMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMahasiswaActionPerformed
        // Tetap bawa namaSesi dan roleSesi supaya pas back nama user nggak hilang
    data_mahasiswa mhs = new data_mahasiswa(namaSesi, roleSesi);
    mhs.setVisible(true);
    mhs.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnMahasiswaActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
    data_dosen dos = new data_dosen(namaSesi, roleSesi);
    dos.setVisible(true);
    dos.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
    data_admin adm = new data_admin(namaSesi, roleSesi);
    adm.setVisible(true);
    adm.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new masteruser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnMahasiswa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
