/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PBO_Project_2;

import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

public class masterdata extends javax.swing.JFrame {
    private static final Logger LOGGER = Logger.getLogger(masterdata.class.getName());

    public masterdata() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(600, 635);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProdi = new javax.swing.JButton();
        btnMatkul = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        back = new javax.swing.JButton();
        btnRuang = new javax.swing.JButton();
        btnKelas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 6, -1, -1));

        btnProdi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnProdi.setText("Data Prodi");
        btnProdi.addActionListener(this::btnProdiActionPerformed);
        getContentPane().add(btnProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, -1));

        btnMatkul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMatkul.setText("Data Matkul");
        btnMatkul.addActionListener(this::btnMatkulActionPerformed);
        getContentPane().add(btnMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 280, -1));

        btnJadwal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnJadwal.setText("Data Jadwal");
        btnJadwal.addActionListener(this::btnJadwalActionPerformed);
        getContentPane().add(btnJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 280, -1));

        back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back.setText("Back");
        back.setToolTipText("");
        back.addActionListener(this::backActionPerformed);
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        btnRuang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRuang.setText("Data Ruang");
        btnRuang.addActionListener(this::btnRuangActionPerformed);
        getContentPane().add(btnRuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, -1));

        btnKelas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnKelas.setText("Data Kelas");
        btnKelas.addActionListener(this::btnKelasActionPerformed);
        getContentPane().add(btnKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 280, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/Master Data.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdiActionPerformed
     new data_prodi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProdiActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      new dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatkulActionPerformed
   new data_matkul().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMatkulActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
    new data_jadwal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void btnRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuangActionPerformed
     new FormRuang().setVisible(true);
    }//GEN-LAST:event_btnRuangActionPerformed

    private void btnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelasActionPerformed
    new FormKelas().setVisible(true);
    }//GEN-LAST:event_btnKelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new masterdata().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnKelas;
    private javax.swing.JButton btnMatkul;
    private javax.swing.JButton btnProdi;
    private javax.swing.JButton btnRuang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
