/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package PBO_Project_2;

import java.sql.*;
import javax.swing.*;
import java.util.HashMap;

public class sign_up extends javax.swing.JFrame {

    // Deklarasi variabel untuk database dan Map
    private database db;
    private HashMap<String, Integer> prodiMap = new HashMap<>();
    private HashMap<String, Integer> dosenMap = new HashMap<>();

    public sign_up() {
        initComponents(); // WAJIB ADA
        this.setSize(1024, 600); // Sesuaikan ukuran
        this.setLocationRelativeTo(null); // Ke tengah layar
        
        db = new database();
        isiComboBox(); // Panggil fungsi isi dropdown
    }

    // Fungsi untuk mengisi Dropdown
    private void isiComboBox() {
        try {
            // Mengisi kotak program studi (jComboBox1)
            ResultSet rsProdi = db.getDaftarProdi();
            jComboBox1.removeAllItems();
            while (rsProdi != null && rsProdi.next()) {
                String nama = rsProdi.getString("nama_prodi");
                int id = rsProdi.getInt("id_prodi");
                jComboBox1.addItem(nama);
                prodiMap.put(nama, id);
            }

           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data dari database: " + e.getMessage());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtSemesterMhs = new javax.swing.JTextField();
        btnShowPassword = new javax.swing.JCheckBox();
        btnShowPassword1 = new javax.swing.JCheckBox();
        btnShowPassword2 = new javax.swing.JCheckBox();
        btnShowPassword3 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 340, 40));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 340, 40));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 340, 40));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 350, 40));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 350, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 230, 50));

        jButton2.setText("Login");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 90, 30));
        getContentPane().add(txtSemesterMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 350, 40));

        btnShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/mata_tertutup.png"))); // NOI18N
        btnShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowPasswordMouseClicked(evt);
            }
        });
        btnShowPassword.addActionListener(this::btnShowPasswordActionPerformed);
        getContentPane().add(btnShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        btnShowPassword1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnShowPassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/mata_tertutup.png"))); // NOI18N
        btnShowPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowPassword1MouseClicked(evt);
            }
        });
        btnShowPassword1.addActionListener(this::btnShowPassword1ActionPerformed);
        getContentPane().add(btnShowPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        btnShowPassword2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnShowPassword2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/mata_tertutup.png"))); // NOI18N
        btnShowPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowPassword2MouseClicked(evt);
            }
        });
        btnShowPassword2.addActionListener(this::btnShowPassword2ActionPerformed);
        getContentPane().add(btnShowPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        btnShowPassword3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnShowPassword3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/mata_tertutup.png"))); // NOI18N
        btnShowPassword3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowPassword3MouseClicked(evt);
            }
        });
        btnShowPassword3.addActionListener(this::btnShowPassword3ActionPerformed);
        getContentPane().add(btnShowPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/sign up.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // 1. Ambil teks (Tambahkan input semester)
        String nama = jTextField1.getText().trim();
        String password = String.valueOf(jPasswordField1.getPassword());
        String confirm = String.valueOf(jPasswordField2.getPassword());
        String angkatanStr = jTextField2.getText().trim();
        String semesterStr = txtSemesterMhs.getText().trim(); // <-- AMBIL INPUT SEMESTER

        // 2. Cek kosong
        if (nama.isEmpty() || password.isEmpty() || confirm.isEmpty() || angkatanStr.isEmpty() || semesterStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua data wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ... (Validasi password dll biarkan sama) ...

       // 4. Proses Simpan
        try {
            int angkatan = Integer.parseInt(angkatanStr); 
            int semesterAktif = Integer.parseInt(semesterStr); // <-- UBAH JADI INTEGER
            
            // --- KODINGAN YANG HILANG (MENGAMBIL ID DARI DROPDOWN) ---
            String prodiTerpilih = jComboBox1.getSelectedItem() != null ? jComboBox1.getSelectedItem().toString() : "";
           
            
            if (prodiTerpilih.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data Prodi belum tersedia!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int idProdi = prodiMap.get(prodiTerpilih);
           
            // ---------------------------------------------------------

            // Panggil method tambahMahasiswa dengan variabel yang benar
            boolean sukses = db.tambahMahasiswa(idProdi, 0, nama, angkatan, semesterAktif, password);
            
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Pendaftaran Berhasil! Silakan Login.");
                new login_form().setVisible(true); 
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Pendaftaran Gagal. Nama mungkin sudah dipakai.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kolom Angkatan dan Semester harus diisi angka bulat!", "Error", JOptionPane.ERROR_MESSAGE);
        }                          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          // Membuka form login dan menutup form sign up
        new login_form().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPasswordMouseClicked

    private void btnShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPasswordActionPerformed
        if (btnShowPassword.isSelected()) {
            // Logika tampilkan password
            jPasswordField1.setEchoChar((char) 0);
            jPasswordField2.setEchoChar((char) 0);
            // Ganti ikon jadi mata terbuka
            btnShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/mata_terbuka.png")));
        } else {
            // Logika sembunyikan password
            jPasswordField1.setEchoChar('*');
            jPasswordField2.setEchoChar('*');
            // Ganti ikon jadi mata tertutup
            btnShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/mata_tertutup.png")));
        }
    }//GEN-LAST:event_btnShowPasswordActionPerformed

    private void btnShowPassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPassword1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPassword1MouseClicked

    private void btnShowPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPassword1ActionPerformed

    private void btnShowPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPassword2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPassword2MouseClicked

    private void btnShowPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPassword2ActionPerformed

    private void btnShowPassword3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowPassword3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPassword3MouseClicked

    private void btnShowPassword3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPassword3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPassword3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
       } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new sign_up().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnShowPassword;
    private javax.swing.JCheckBox btnShowPassword1;
    private javax.swing.JCheckBox btnShowPassword2;
    private javax.swing.JCheckBox btnShowPassword3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtSemesterMhs;
    // End of variables declaration//GEN-END:variables
}
