/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package PBO_Project_2;

import java.sql.*;
import javax.swing.*;
import java.util.HashMap;

public class sign_up extends javax.swing.JFrame {

    // Deklarasi variabel untuk database dan Map
    private database db;
    private HashMap<String, Integer> prodiMap = new HashMap<>();
    private HashMap<String, Integer> dosenMap = new HashMap<>();

    public sign_up() {
        initComponents(); // WAJIB ADA
        this.setSize(1024, 600); // Sesuaikan ukuran
        this.setLocationRelativeTo(null); // Ke tengah layar
        
        db = new database();
        isiComboBox(); // Panggil fungsi isi dropdown
    }

    // Fungsi untuk mengisi Dropdown
    private void isiComboBox() {
        try {
            // Mengisi kotak program studi (jComboBox1)
            ResultSet rsProdi = db.getDaftarProdi();
            jComboBox1.removeAllItems();
            while (rsProdi != null && rsProdi.next()) {
                String nama = rsProdi.getString("nama_prodi");
                int id = rsProdi.getInt("id_prodi");
                jComboBox1.addItem(nama);
                prodiMap.put(nama, id);
            }

            // Mengisi kotak dosen pa (jComboBox2)
            ResultSet rsDosen = db.getDaftarDosen();
            jComboBox2.removeAllItems();
            while (rsDosen != null && rsDosen.next()) {
                String nama = rsDosen.getString("nama_dosen");
                int id = rsDosen.getInt("id_dosen");
                jComboBox2.addItem(nama);
                dosenMap.put(nama, id);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data dari database: " + e.getMessage());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 340, 40));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 340, 40));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 340, 40));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 350, 40));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 350, 40));

        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 350, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 230, 50));

        jButton2.setText("Login");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desain/sign up.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // 1. Ambil teks dari kotak-kotak input Anda
        String nama = jTextField1.getText().trim();
        String password = String.valueOf(jPasswordField1.getPassword());
        String confirm = String.valueOf(jPasswordField2.getPassword());
        String angkatanStr = jTextField2.getText().trim();
        
        // 2. Cek kosong
        if (nama.isEmpty() || password.isEmpty() || confirm.isEmpty() || angkatanStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua data wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Cek kesamaan password
        if (!password.equals(confirm)) {
            JOptionPane.showMessageDialog(this, "Password dan Konfirmasi Password tidak cocok!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Proses Simpan
        try {
            int angkatan = Integer.parseInt(angkatanStr); 
            
            String prodiTerpilih = jComboBox1.getSelectedItem() != null ? jComboBox1.getSelectedItem().toString() : "";
            String dosenTerpilih = jComboBox2.getSelectedItem() != null ? jComboBox2.getSelectedItem().toString() : "";
            
            if (prodiTerpilih.isEmpty() || dosenTerpilih.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Data Prodi atau Dosen PA belum tersedia!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int idProdi = prodiMap.get(prodiTerpilih);
            int idDosenPA = dosenMap.get(dosenTerpilih);

            boolean sukses = db.tambahMahasiswa(idProdi, idDosenPA, nama, angkatan, password);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Pendaftaran Berhasil! Silakan Login.");
                new login_form().setVisible(true); 
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Pendaftaran Gagal. Nama mungkin sudah dipakai.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kolom Angkatan harus diisi angka (contoh: 2024)!", "Error", JOptionPane.ERROR_MESSAGE);
        }
                                           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          // Membuka form login dan menutup form sign up
        new login_form().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
       } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new sign_up().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
